### ISSUE TITLE
Internal Error when typing /sentry guard [playername]

### ISSUE THREAD

**Issue by tmfksoft** [jrbudda/Sentry#110]
When I type '/sentry guard TMFKSOFT' In Game I receive the message:
An internal error occured when attempting to perform this command

In my Server Console I Recieve:

04:45:28 [INFO] TMFKSOFT issued server command: /sentry guard TMFKSOFT
04:45:28 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'sentry' in plugin Sentry v1.3.3.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.dispatchCommand(CraftServer.java:523)
        at net.minecraft.server.v1_5_R3.PlayerConnection.handleCommand(PlayerConnection.java:965)
        at net.minecraft.server.v1_5_R3.PlayerConnection.chat(PlayerConnection.java:883)
        at net.minecraft.server.v1_5_R3.PlayerConnection.a(PlayerConnection.java:840)
        at net.minecraft.server.v1_5_R3.Packet3Chat.handle(Packet3Chat.java:44)
        at net.minecraft.server.v1_5_R3.NetworkManager.b(NetworkManager.java:292)
        at net.minecraft.server.v1_5_R3.PlayerConnection.d(PlayerConnection.java:109)
        at net.minecraft.server.v1_5_R3.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:581)
        at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
        at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
        at net.aufdemrand.sentry.Sentry.onCommand(Sentry.java:717)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        ... 15 more

Im currently using:
Bukkit for Minecraft 1.5.2 [Latest Dev]
Citizens 2.0.8 (Alpha 4)
Sentry v1.3.3.3 4/9/2013

**Comment by Paul0000** [comment]
i think, Sentry isn´t updatet jet. I didnt have problems with 1.5.1 but in 1.5.2 i have the same problem than you.

**Comment by XxCoolGamesxX** [comment]
He it not update for 1.5.2 but I it a pull requests: https://github.com/jrbudda/Sentry/pull/112
