### ISSUE TITLE
Sentry Does No Damage In Guard Mode, Retaliate = True, Target entity:monster

### ISSUE THREAD

**Issue by Silverbane** [jrbudda/Sentry#137]
See ticket in citizens bugs.
http://issues.citizensnpcs.com/browse/CITIZENS-294

Update - When I rename the sentry to my name everything works fine. So I gave the sentry a different name and added that sentry name to the groups I was in for permissionsex and set the npc to playerlist but that still did not work. So for now I will use variable triggers to add /npc rename <playername> whenever someone puts a sentry on guard <playername> for a temp fix. But I am hoping we can figure out how to fix this issue instead of using this work around.

As the title states, the sentry does no damage to the monster even though the combat animation is on. Damage from sentry is normal until I apply the /sentry guard command. Steps: 1. Create sentry 2. Assign target entity:monster 3. Set guard to me. retaliate is set to true in config.yml.

I am having this issue as well.
Here are the plugins I have loading in: http://pastebin.com/HnKwyXxJ
Note this only happens in guard mode, all other modes do damage just fine.
And this is the only bug that I keep see appearing when this incident is happening but have no idea if it related or not.
2013-06-24 05:12:43 [WARNING] [MobHealth] Task #86069 for MobHealth v6.1.4 generated an exception
java.lang.NullPointerException
at me.ThaH3lper.com.Api.Api.getMaxHealth(Api.java:33)
at me.sablednah.MobHealth.API.MobHealthAPI.getMobMaxHealth(MobHealthAPI.java:349)
at me.sablednah.MobHealth.API.MobHealthAPI.showBar(MobHealthAPI.java:452)
at me.sablednah.MobHealth.ServerDamageEntityListener$ScheduledshowBar.run(ServerDamageEntityListener.java:198)
at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
Any help would be much appreciated.

**Comment by jrbudda** [comment]
Has to be a plugin conflict of some type, the MobHealth error may be related. Try disabling plugins one at a time to see if it goes away. Sentries in bodyguard mode obey damage protection plugins.

**Comment by jrbudda** [comment]
The new option in sentry 1.3.7+ should fix your compatibility problem.
