### ISSUE TITLE
Problem with the #5192 task.

### ISSUE THREAD

**Issue by sergioblesa** [jrbudda/Sentry#14]
I created a Sentry that should follow and kill monsters. But when I spawn a monster near him to test it, he looks at it but doesn't move, while the console shows this:

17:14:30 [ADVERTENCIA] [Sentry] Task #46 for Sentry v0.9.1 generated an exceptio
n
java.lang.IllegalStateException: not navigating
        at net.citizensnpcs.npc.ai.CitizensNavigator.getLocalParameters(Citizens
Navigator.java:58)
        at net.aufdemrand.sentry.SentryInstance.setTarget(SentryInstance.java:12
04)
        at net.aufdemrand.sentry.SentryInstance$SentryLogicRunnable.run(SentryIn
stance.java:104)
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:52)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:316)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:510)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

Could anyone help me please? Thank you and forgive my bad English xD

**Comment by jrbudda** [comment]
fixed
