### ISSUE TITLE
An error keeps spamming the console

### ISSUE THREAD

**Issue by sergioblesa** [jrbudda/Sentry#16]
I think it does not affect the game, but it's a bit annoying:

16:33:45 [GRAVE] Could not pass event EntityTargetEvent to Citizens
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:332)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:462)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityTargetEvent(
CraftEventFactory.java:464)
        at net.minecraft.server.PathfinderGoalMeleeAttack.c(PathfinderGoalMeleeA
ttack.java:59)
        at net.minecraft.server.PathfinderGoalSelector.a(PathfinderGoalSelector.
java:62)
        at net.minecraft.server.EntityLiving.bc(EntityLiving.java:1216)
        at net.minecraft.server.EntityLiving.d(EntityLiving.java:1091)
        at net.minecraft.server.EntityMonster.d(EntityMonster.java:21)
        at net.minecraft.server.EntityZombie.d(EntityZombie.java:55)
        at net.minecraft.server.EntityLiving.h_(EntityLiving.java:447)
        at net.minecraft.server.EntityMonster.h_(EntityMonster.java:25)
        at net.minecraft.server.World.entityJoinedWorld(World.java:1245)
        at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:5
11)
        at net.minecraft.server.World.playerJoinedWorld(World.java:1227)
        at net.minecraft.server.World.tickEntities(World.java:1125)
        at net.minecraft.server.WorldServer.tickEntities(WorldServer.java:428)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:564)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.IllegalArgumentException: The validated object is null
        at org.apache.commons.lang.Validate.notNull(Validate.java:222)
        at net.citizensnpcs.npc.CitizensNPCRegistry.getNPC(CitizensNPCRegistry.j
ava:143)
        at net.citizensnpcs.npc.CitizensNPCRegistry.isNPC(CitizensNPCRegistry.ja
va:150)
        at net.citizensnpcs.EventListen.onEntityTarget(EventListen.java:150)
        at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:330)
        ... 22 more

**Comment by jrbudda** [comment]
Update to the latest build of citizens 2
