### ISSUE TITLE
Sentry not dying

### ISSUE THREAD

**Issue by Dengarian** [jrbudda/Sentry#162]
Hi,

Using CraftBukkit version git-Bukkit-1.6.2-R0.1-b2838jnks (MC: 1.6.2) (Implementing API version 1.6.2-R0.1) with citizens-2.0.9-SNAPSHOT.jar and denizen-0.9.1-SNAPSHOT.jar and the Sentry.jar (version 1.5.2).

I can create an NPC fine and assign the sentry trait, however, when attacking the sentry it retaliates but eventually gives up and constant attacking does not kill it. I notice in the server log when this happens the following entry occurs:

16:28:24 [SEVERE] Could not pass event EntityDamageByEntityEvent to Sentry v1.5.
2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:462)
        at org.bukkit.craftbukkit.v1_6_R2.event.CraftEventFactory.callEvent(Craf
tEventFactory.java:93)
        at org.bukkit.craftbukkit.v1_6_R2.event.CraftEventFactory.callEntityDama
geEvent(CraftEventFactory.java:381)
        at org.bukkit.craftbukkit.v1_6_R2.event.CraftEventFactory.handleEntityDa
mageEvent(CraftEventFactory.java:406)
        at net.minecraft.server.v1_6_R2.EntityLiving.damageEntity(EntityLiving.j
ava:636)
        at net.minecraft.server.v1_6_R2.EntityHuman.damageEntity(EntityHuman.jav
a:714)
        at net.minecraft.server.v1_6_R2.EntityPlayer.damageEntity(EntityPlayer.j
ava:378)
        at net.minecraft.server.v1_6_R2.EntityHuman.attack(EntityHuman.java:884)

```
    at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java
```

:1121)
        at net.minecraft.server.v1_6_R2.Packet7UseEntity.handle(SourceFile:36)
        at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296
)
        at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java
:116)
        at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
        at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:3
0)
        at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:5
90)
        at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:2
26)
        at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:4
86)
        at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java
:419)
        at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:5
82)
Caused by: java.lang.NoSuchMethodError: net.aufdemrand.denizen.objects.dPlayer.m
irrorBukkitPlayer(Lorg/bukkit/OfflinePlayer;)Lnet/aufdemrand/denizen/objects/dPl
ayer;
        at net.aufdemrand.sentry.DenizenHook.DenizenAction(DenizenHook.java:70)
        at net.aufdemrand.sentry.SentryInstance.die(SentryInstance.java:476)
        at net.aufdemrand.sentry.SentryInstance.onDamage(SentryInstance.java:121
9)
        at net.aufdemrand.sentry.SentryListener.onDamage(SentryListener.java:302
)
        at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:425)
        ... 21 more

A /sentry info then shows the sentry as having only 2 out of 20 health. An additional attack on that sentry causes the same error and will not kill the sentry. I've recreated this time and time again.

Let me know if you need any further.

**Comment by BucketFreak** [comment]
Hi!

I'm experiening the same problem and see the same error.

The console also says something about the NPCDEATH and NPCDEATHOWNER Trigger.

I already tried assign a script that catches the NPCDEATH trigger but that only changes the error (Error while parsing NPCDEATH trigger ... error while passing java.lang......die command).

Hope this helps.

**Comment by xMacabrex** [comment]
I've noticed that npcs wont drop below 1 hp, check to see if this is the same for you guys.

**Comment by Dengarian** [comment]
@xMacabrex yep have had this issue as well.

**Comment by xMacabrex** [comment]
@Dengarian
Okay, lets see if we have same plugins:
Citizens (duh)
Denizens, sentry, dtltraders.

**Comment by xMacabrex** [comment]
@jrbudda @Dengarian @BucketFreak 

I've found the problem with npc's not dying:

This was given after I killed a non-sentry npc and tried to see it's health using /npc he ( or /npc health):
13.09 13:03:16 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
13.09 13:03:16 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
13.09 13:03:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
13.09 13:03:16 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
13.09 13:03:16 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_5_R3.World

The npc couldn't respawn after that!
The problem may not be with sentry but with citizens! o:

**Comment by XxCoolGamesxX** [comment]
It you download the Last Sentry and Citizens ? Look like you use old one.

**Comment by xMacabrex** [comment]
@XxCoolGamesxX 
Citizens: Version 2.0.9-SNAPSHOT (build 966) by aPunch
Sentry: Version 1.5.2 by jrbudda

**Comment by XxCoolGamesxX** [comment]
One download the last dev of http://ci.citizensnpcs.co/job/Citizens2/changes and download the last of 1.5.2 again http://wiki.citizensnpcs.co/Sentry and be sure you update your craftbukkit to last update. 

Can you give me more info on the error because you only gave me half of it.

**Comment by mcmonkey4eva** [comment]
@Dengarian @BucketFreak @xMacabrex -
Denizen 0.9.1 is incredibly old... the bukkit dev has fallen out of date... (But with a recommended version of craftbukkit 1.6 out and all that, it should be updated soon)

Until it's updated, please download 0.9.2 from here: http://jenkins.citizensnpcs.co/job/Denizen/
Every error posted in this thread was caused by using an outdated Denizen built for 1.5.2.

**Comment by xMacabrex** [comment]
@XxCoolGamesxX 

That was all I got, the rest was put into a "skipped: 'X' lines due to rate"
Sorry.
