### ISSUE TITLE
Sentry errors

### ISSUE THREAD

**Issue by Deimos161** [jrbudda/Sentry#168]
I am getting a few issue with Sentry.
I am using Sentry v1.5.3 and Citizens v2.0.9-SNAPSHOT

I get the following errors:
2013-09-22 17:36:20 [INFO] deimos161 issued server command: /npc spawn 54
2013-09-22 17:36:20 [SEVERE] [Citizens] An exception occurred while the trait sentry was spawning for NPC ID 54.
2013-09-22 17:36:20 [SEVERE] java.lang.NoClassDefFoundError: net/minecraft/server/v1_6_R3/Packet
2013-09-22 17:36:20 [SEVERE]    at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:133)
2013-09-22 17:36:20 [SEVERE]    at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:115)
2013-09-22 17:36:20 [SEVERE]    at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:182)
2013-09-22 17:36:20 [SEVERE]    at net.citizensnpcs.commands.NPCCommands.spawn(NPCCommands.java:1085)
2013-09-22 17:36:20 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-09-22 17:36:20 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-09-22 17:36:20 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-09-22 17:36:20 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-09-22 17:36:20 [SEVERE]    at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:153)
2013-09-22 17:36:20 [SEVERE]    at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
2013-09-22 17:36:20 [SEVERE]    at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:177)
2013-09-22 17:36:20 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:214)
2013-09-22 17:36:20 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-09-22 17:36:20 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
2013-09-22 17:36:20 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:523)
2013-09-22 17:36:20 [SEVERE]    at net.minecraft.server.v1_6_R2.PlayerConnection.handleCommand(PlayerConnection.java:954)
2013-09-22 17:36:20 [SEVERE]    at net.minecraft.server.v1_6_R2.PlayerConnection.chat(PlayerConnection.java:872)
2013-09-22 17:36:20 [SEVERE]    at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:829)
2013-09-22 17:36:20 [SEVERE]    at net.minecraft.server.v1_6_R2.Packet3Chat.handle(SourceFile:49)
2013-09-22 17:36:20 [SEVERE]    at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296)
2013-09-22 17:36:20 [SEVERE]    at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116)
2013-09-22 17:36:20 [SEVERE]    at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
2013-09-22 17:36:20 [SEVERE]    at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30)
2013-09-22 17:36:20 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590)
2013-09-22 17:36:20 [SEVERE]    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
2013-09-22 17:36:20 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
2013-09-22 17:36:20 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
2013-09-22 17:36:20 [SEVERE]    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
2013-09-22 17:36:20 [SEVERE] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_6_R3.Packet
2013-09-22 17:36:20 [SEVERE]    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
2013-09-22 17:36:20 [SEVERE]    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
2013-09-22 17:36:20 [SEVERE]    at java.lang.ClassLoader.loadClass(Unknown Source)
2013-09-22 17:36:20 [SEVERE]    at java.lang.ClassLoader.loadClass(Unknown Source)
2013-09-22 17:36:20 [SEVERE]    ... 28 more

2013-09-22 17:36:47 [INFO] deimos161 issued server command: /trait sentry
2013-09-22 17:36:47 [SEVERE] java.lang.NoClassDefFoundError: net/minecraft/server/v1_6_R3/Packet
2013-09-22 17:36:47 [SEVERE]    at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:133)
2013-09-22 17:36:47 [SEVERE]    at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:115)
2013-09-22 17:36:47 [SEVERE]    at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:106)
2013-09-22 17:36:47 [SEVERE]    at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:85)
2013-09-22 17:36:47 [SEVERE]    at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:59)
2013-09-22 17:36:47 [SEVERE]    at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:152)
2013-09-22 17:36:47 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2013-09-22 17:36:47 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2013-09-22 17:36:47 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2013-09-22 17:36:47 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2013-09-22 17:36:47 [SEVERE]    at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:153)
2013-09-22 17:36:47 [SEVERE]    at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
2013-09-22 17:36:47 [SEVERE]    at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:177)
2013-09-22 17:36:47 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:214)
2013-09-22 17:36:47 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2013-09-22 17:36:47 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
2013-09-22 17:36:47 [SEVERE]    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:523)
2013-09-22 17:36:47 [SEVERE]    at net.minecraft.server.v1_6_R2.PlayerConnection.handleCommand(PlayerConnection.java:954)
2013-09-22 17:36:47 [SEVERE]    at net.minecraft.server.v1_6_R2.PlayerConnection.chat(PlayerConnection.java:872)
2013-09-22 17:36:47 [SEVERE]    at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:829)
2013-09-22 17:36:47 [SEVERE]    at net.minecraft.server.v1_6_R2.Packet3Chat.handle(SourceFile:49)
2013-09-22 17:36:47 [SEVERE]    at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296)
2013-09-22 17:36:47 [SEVERE]    at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116)
2013-09-22 17:36:47 [SEVERE]    at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
2013-09-22 17:36:47 [SEVERE]    at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30)
2013-09-22 17:36:47 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590)
2013-09-22 17:36:47 [SEVERE]    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
2013-09-22 17:36:47 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
2013-09-22 17:36:47 [SEVERE]    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
2013-09-22 17:36:47 [SEVERE]    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
2013-09-22 17:36:47 [SEVERE] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_6_R3.Packet
2013-09-22 17:36:47 [SEVERE]    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
2013-09-22 17:36:47 [SEVERE]    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
2013-09-22 17:36:47 [SEVERE]    at java.lang.ClassLoader.loadClass(Unknown Source)
2013-09-22 17:36:47 [SEVERE]    at java.lang.ClassLoader.loadClass(Unknown Source)
2013-09-22 17:36:47 [SEVERE]    ... 30 more

2013-09-22 17:38:20 [INFO] deimos161 issued server command: /sentry guard deimos161
2013-09-22 17:38:20 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'sentry' in plugin Sentry v1.5.3
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:523)
    at net.minecraft.server.v1_6_R2.PlayerConnection.handleCommand(PlayerConnection.java:954)
    at net.minecraft.server.v1_6_R2.PlayerConnection.chat(PlayerConnection.java:872)
    at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:829)
    at net.minecraft.server.v1_6_R2.Packet3Chat.handle(SourceFile:49)
    at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296)
    at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116)
    at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
    at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590)
    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
Caused by: java.lang.NullPointerException
    at net.aufdemrand.sentry.Sentry.onCommand(Sentry.java:763)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    ... 15 more

**Comment by jrbudda** [comment]
looks like youre trying to use Sentry for craftbukkit 1.6.4 on 1.6.2

**Comment by Deimos161** [comment]
_Sigh_ yep that would be it. Sorry matey. I totally forgot that 1.6.4 even came out.
