### ISSUE TITLE
Centry Error

### ISSUE THREAD

**Issue by Reverof82** [jrbudda/Sentry#169]
In game it said "Please report this issue [see console]

and in the console it had this:

java.lang.NoClassDefFoundError: net/minecraft/server/v1_6_R2/Packet
      at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:133)
      at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:115)
      at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:108)
      at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:87)
      at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:59)
      at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:152)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      at java.lang.reflect.Method.invoke(Unknown Source)
      at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:153)
      at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
      at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:177)
      at net.citizensnpcs.Citizens.onCommand(Citizens.java:214)
      at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
      at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
      at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(CraftServer.java:523)
      at net.minecraft.server.v1_6_R3.PlayerConnection.handleCommand(PlayerConnection.java:959)
      at net.minecraft.server.v1_6_R3.PlayerConnection.chat(PlayerConnection.java:877)
      at net.minecraft.server.v1_6_R3.PlayerConnection.a(PlayerConnection.java:834)
      at net.minecraft.server.v1_6_R3.Packet3Chat.handle(SourceFile:49)
      at net.minecraft.server.v1_6_R3.NetworkManager.b(NetworkManager.java:296)
      at net.minecraft.server.v1_6_R3.PlayerConnection.e(PlayerConnection.java:116)
      at net.minecraft.server.v1_6_R3.ServerConnection.b(SourceFile:37)
      at net.minecraft.server.v1_6_R3.DedicatedServerConnection.b(SourceFile:30)
      at net.minecraft.server.v1_6_R3.MinecraftServer.t(MinecraftServer.java:592)
      at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:227)
      at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:488)
      at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:421)

**Comment by jrbudda** [comment]
You're trying to use Sentry for 1.6.2 on 1.6.4

**Comment by Reverof82** [comment]
doh! I thought I got the latest, thanks!

**Comment by Reverof82** [comment]
Ok, now that that issue is resolved... I have seemed to notice that, atleast on my server the mobs will only attack the NPCs if hey have a Players name... if I name one Guard no mobs will attack him ... but if I change the exact same NPCs name to my name Reverof82 the mobs will attack him right away... anyone else have this issue? I have tried this with various names.
