### ISSUE TITLE
trait not working

### ISSUE THREAD

**Issue by ozm8** [jrbudda/Sentry#179]
I cant get this trait to work I have tried the latest build for citizens bukkit and sentry but still comes up with an error when I /trait sentry

4:26:56 AM
 CONSOLE:
[SEVERE] java.lang.NoClassDefFoundError: net/minecraft/server/v1_6_R2/Packet
4:26:56 AM
 CONSOLE:
[SEVERE] at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:133)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:115)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:113)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:92)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:59)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:152)
4:26:56 AM
 CONSOLE:
[SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
4:26:56 AM
 CONSOLE:
[SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
4:26:56 AM
 CONSOLE:
[SEVERE] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
4:26:56 AM
 CONSOLE:
[SEVERE] at java.lang.reflect.Method.invoke(Unknown Source)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:153)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:177)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.citizensnpcs.Citizens.onCommand(Citizens.java:215)
4:26:56 AM
 CONSOLE:
[SEVERE] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
4:26:56 AM
 CONSOLE:
[SEVERE] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
4:26:56 AM
 CONSOLE:
[SEVERE] at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(CraftServer.java:528)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.PlayerConnection.handleCommand(PlayerConnection.java:968)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.PlayerConnection.chat(PlayerConnection.java:886)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.PlayerConnection.a(PlayerConnection.java:837)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.Packet3Chat.handle(SourceFile:49)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.NetworkManager.b(NetworkManager.java:296)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.PlayerConnection.e(PlayerConnection.java:116)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.ServerConnection.b(SourceFile:37)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.DedicatedServerConnection.b(SourceFile:30)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.t(MinecraftServer.java:592)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:227)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:488)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:421)
4:26:56 AM
 CONSOLE:
[SEVERE] at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)
4:26:56 AM
 CONSOLE:
[SEVERE] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_6_R2.Packet
4:26:56 AM
 CONSOLE:
[SEVERE] at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
4:26:56 AM
 CONSOLE:
[SEVERE] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
4:26:56 AM
 CONSOLE:
[SEVERE] at java.lang.ClassLoader.loadClass(Unknown Source)
4:26:56 AM
 CONSOLE:
[SEVERE] at java.lang.ClassLoader.loadClass(Unknown Source)

**Comment by mcmonkey4eva** [comment]
@ozm8 

make sure you're running the latest Sentry from: http://wiki.citizensnpcs.co/Sentry
and latest Citizens from: http://ci.citizensnpcs.co/job/Citizens2/

**Comment by adamwbb** [comment]
same here im running the latest version of citizens and sentry for 1.6.4 im running craftbukkit 1.6.4
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:421)
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:488)
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:227)
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.t(MinecraftServer.java:524)
2013-12-07 05:53:05 [SEVERE] at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
2013-12-07 05:53:05 [SEVERE] at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftTask.run(CraftTask.java:53)
2013-12-07 05:53:05 [SEVERE] at net.citizensnpcs.Citizens$1.run(Citizens.java:273)
2013-12-07 05:53:05 [SEVERE] at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:55)
2013-12-07 05:53:05 [SEVERE] at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:108)
2013-12-07 05:53:05 [SEVERE] at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:184)
2013-12-07 05:53:05 [SEVERE] at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:130)
2013-12-07 05:53:05 [SEVERE] at net.aufdemrand.sentry.SentryInstance.initialize(SentryInstance.java:968)
2013-12-07 05:53:05 [SEVERE] at net.aufdemrand.sentry.SentryInstance.setHealth(SentryInstance.java:1555)
2013-12-07 05:53:05 [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.getEntity()Lorg/bukkit/entity/Entity;
2013-12-07 05:53:05 [SEVERE] [Citizens] An exception occurred while the trait sentry was spawning for NPC ID 92.
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:421)
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:488)
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:227)
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.t(MinecraftServer.java:524)
2013-12-07 05:53:05 [SEVERE] at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
2013-12-07 05:53:05 [SEVERE] at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftTask.run(CraftTask.java:53)
2013-12-07 05:53:05 [SEVERE] at net.citizensnpcs.Citizens$1.run(Citizens.java:273)
2013-12-07 05:53:05 [SEVERE] at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:55)
2013-12-07 05:53:05 [SEVERE] at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:108)
2013-12-07 05:53:05 [SEVERE] at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:184)
2013-12-07 05:53:05 [SEVERE] at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:130)
2013-12-07 05:53:05 [SEVERE] at net.aufdemrand.sentry.SentryInstance.initialize(SentryInstance.java:956)
2013-12-07 05:53:05 [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.getEntity()Lorg/bukkit/entity/Entity;
2013-12-07 05:53:05 [SEVERE] [Citizens] An exception occurred while the trait sentry was spawning for NPC ID 65.
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:421)
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:488)
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:227)
2013-12-07 05:53:05 [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.t(MinecraftServer.java:524)
2013-12-07 05:53:05 [SEVERE] at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
2013-12-07 05:53:05 [SEVERE] at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftTask.run(CraftTask.java:53)
2013-12-07 05:53:05 [SEVERE] at net.citizensnpcs.Citizens$1.run(Citizens.java:273)
2013-12-07 05:53:05 [SEVERE] at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:55)
2013-12-07 05:53:05 [SEVERE] at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:108)
2013-12-07 05:53:05 [SEVERE] at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:184)
2013-12-07 05:53:05 [SEVERE] at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:130)
2013-12-07 05:53:05 [SEVERE] at net.aufdemrand.sentry.SentryInstance.initialize(SentryInstance.java:968)
2013-12-07 05:53:05 [SEVERE] at net.aufdemrand.sentry.SentryInstance.setHealth(SentryInstance.java:1555)
2013-12-07 05:53:05 [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.getEntity()Lorg/bukkit/entity/Entity;
2013-12-07 05:53:05 [SEVERE] [Citizens] An exception occurred while the trait sentry was spawning for NPC ID 5.
2013-12-07 05:53:05 [INFO] [Sentry] Registered sucessfully with Vault: 10 groups found. The GROUP: target will function

**Comment by mcmonkey4eva** [comment]
@adamwbb You're running a really old version of Citizens, update to this one: http://ci.citizensnpcs.co/job/Citizens2/1021/
