### ISSUE TITLE
Teleporting Causes Server Crash

### ISSUE THREAD

**Issue by ctark** [jrbudda/Sentry#19]
21:16:12 [INFO] [PLAYER_COMMAND] ctark: /tp sport
21:16:15 [SEVERE] java.lang.AbstractMethodError: net.aufdemrand.sentry.BodyguardTeleportStuckAction.run(Lnet/citizensnpcs/api/npc/NPC;Lnet/citizensnpcs/api/ai/Navigator;)V
21:16:15 [SEVERE]       at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:145)
21:16:15 [SEVERE]       at net.citizensnpcs.npc.ai.CitizensNavigator.updateStationaryStatus(CitizensNavigator.java:183)
21:16:15 [SEVERE]       at net.citizensnpcs.npc.ai.CitizensNavigator.update(CitizensNavigator.java:160)
21:16:15 [SEVERE]       at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:163)
21:16:15 [SEVERE]       at net.citizensnpcs.npc.entity.CitizensHumanNPC.update(CitizensHumanNPC.java:138)
21:16:15 [SEVERE]       at net.citizensnpcs.npc.entity.EntityHumanNPC.h_(EntityHumanNPC.java:85)
21:16:15 [SEVERE]       at net.minecraft.server.World.entityJoinedWorld(World.java:1239)
21:16:15 [SEVERE]       at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:498)
21:16:15 [SEVERE]       at net.minecraft.server.World.playerJoinedWorld(World.java:1221)
21:16:15 [SEVERE]       at net.minecraft.server.World.tickEntities(World.java:1119)
21:16:15 [SEVERE]       at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:567)
21:16:15 [SEVERE]       at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
21:16:15 [SEVERE]       at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:476)
21:16:15 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
21:16:15 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
21:16:15 [SEVERE] Encountered an unexpected exception AbstractMethodError
java.lang.AbstractMethodError: net.aufdemrand.sentry.BodyguardTeleportStuckAction.run(Lnet/citizensnpcs/api/npc/NPC;Lnet/citizensnpcs/api/ai/Navigator;)V
        at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:145)
        at net.citizensnpcs.npc.ai.CitizensNavigator.updateStationaryStatus(CitizensNavigator.java:183)
        at net.citizensnpcs.npc.ai.CitizensNavigator.update(CitizensNavigator.java:160)
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:163)
        at net.citizensnpcs.npc.entity.CitizensHumanNPC.update(CitizensHumanNPC.java:138)
        at net.citizensnpcs.npc.entity.EntityHumanNPC.h_(EntityHumanNPC.java:85)
        at net.minecraft.server.World.entityJoinedWorld(World.java:1239)
        at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:498)
        at net.minecraft.server.World.playerJoinedWorld(World.java:1221)
        at net.minecraft.server.World.tickEntities(World.java:1119)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:567)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:476)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

This happens when you teleport somewhere, or use something like '/home'

Used the Hire Mercenary Tutorial, copy paste, no changes:
http://wiki.citizensnpcs.com/Sentry/Sentry_and_Denizen

Obviously I would say this is a HUGE bug, since almost every server has teleportation in some manor, and it looks like you have some support for it, but something is happening thats crashing the server, hopefully nothing big.

**Comment by jrbudda** [comment]
Use build 334+ of citizens2. theres a link at the top of the Sentry wiki page.
