### ISSUE TITLE
1.8.0 No such method error on sentry kill/retarget

### ISSUE THREAD

**Issue by BriannaThorez** [jrbudda/Sentry#197]
Hello

When I attack a sentry and he comes to retaliate on his first hit on me console returns the following error. It is not repetative. I happens on the first attack of each time he retaliates.
Spigot build 1300 for MC1.7.2
Latest sentry/citizens builds

It seems to have something to do with post kill logic since the error will not show up untill the sentry decides the target is no longer killable(aka dead or in creative).

Apparently a known bug but I forgot to post here.

[22:02:34] [Server thread/WARN]: [Sentry] Task #95 for Sentry v1.8.0 generated an exception
java.lang.NoSuchMethodError net.citizensnpcs.util.NMS.sendPacketsNearby(Lorg/bukkit/Location;[Lnet/minecraft/server/v1_7_R1/Packet;)V
    at net.aufdemrand.sentry.SentryInstance$SentryLogic.run(SentryInstance.java:1420) ~[?:?]
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[spigot172.jar:git-Spigot-1300]
    at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [spigot172.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:612) [spigot172.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [spigot172.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:560) [spigot172.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:467) [spigot172.jar:git-Spigot-1300]
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot172.jar:git-Spigot-1300]

**Comment by mcmonkey4eva** [comment]
Known issue, nothing we can do about it until @jrbudda awakens from his eternal slumber once more and either lets me/other devs contribute to Sentry or gets active and fixes issues himself

For now, switch to Sentry v1.7.1 from the wiki -> https://github.com/jrbudda/Sentry -> it doesn't have the error.
If you don't trust the wiki link, you can get the latest dev build from the official Citizens repo -> http://ci.citizensnpcs.co/job/Sentry/ (which is v1.7.1, as @jrbudda created v1.8.0 and deleted everything that makes up 1.7.1, include the parts that let it work on the Citizens repo)
