### ISSUE TITLE
No implementation set console spam

### ISSUE THREAD

**Issue by BriannaThorez** [jrbudda/Sentry#199]
Spigot build 1300
Sentry latest devbuild
Citizens 2.0.11
After creating an NPC, doing /trait sentry, equipping the sentry using /sentry equip, and attacking the sentry a few times I notice his gear is not reloading(known citizenz bug) So i do /citizens save, /citizens reload, and exit/relog to my server. The gear is loaded but when I attack the sentry he shows the wrong health. Then I do /sentry health and it tells me the correct value I had set. then I do /citizens reload /sentry reload and the sentry duplicates(a ghost is left behind). Console then spams this.

A frequent and unavoidable issue for me when creating any new sentrys sans the ones i've already got.

[00:56:00] [Server thread/INFO]: [Citizens] Exception while updating 13: no implementation set.
[00:56:00] [Server thread/WARN]: java.lang.IllegalStateException: no implementation set
[00:56:00] [Server thread/WARN]:    at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:70)
[00:56:00] [Server thread/WARN]:    at net.citizensnpcs.api.CitizensAPI.getNPCRegistry(CitizensAPI.java:103)
[00:56:00] [Server thread/WARN]:    at net.citizensnpcs.trait.LookClose.findNewTarget(LookClose.java:58)
[00:56:00] [Server thread/WARN]:    at net.citizensnpcs.trait.LookClose.run(LookClose.java:98)
[00:56:00] [Server thread/WARN]:    at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:425)
[00:56:00] [Server thread/WARN]:    at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:216)
[00:56:00] [Server thread/WARN]:    at net.citizensnpcs.npc.entity.EntityHumanNPC.h(EntityHumanNPC.java:175)
[00:56:00] [Server thread/WARN]:    at net.minecraft.server.v1_7_R1.World.entityJoinedWorld(World.java:1472)
[00:56:00] [Server thread/WARN]:    at net.minecraft.server.v1_7_R1.World.playerJoinedWorld(World.java:1448)
[00:56:00] [Server thread/WARN]:    at net.minecraft.server.v1_7_R1.World.tickEntities(World.java:1317)
[00:56:00] [Server thread/WARN]:    at net.minecraft.server.v1_7_R1.WorldServer.tickEntities(WorldServer.java:514)
[00:56:00] [Server thread/WARN]:    at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:671)
[00:56:00] [Server thread/WARN]:    at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273)
[00:56:00] [Server thread/WARN]:    at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:560)
[00:56:00] [Server thread/WARN]:    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:467)
[00:56:00] [Server thread/WARN]:    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617)

**Comment by fullwall** [comment]
Can you pastebin your startup log?

**Comment by BriannaThorez** [comment]
http://pastebin.com/BEPfDAeN
Here is my server startup log

I think this is related to a citizens/sentry stat conflict i've ticketed on citizen's site.
     I create an NPC set his name "test" health "250" strength "1" and do /sentry equip iron_leggings...
     Hit him, health shows 249/250. the armor leggings do not load(are not visible)
     exit server, do console /citizens reload
     I rejoin and TP to sentry, his leggings are loaded(after a few tries) 
     I hit him and his health shows 59/60(incorrectly from how I configured it, as this is default sentry health) He retaliates(against my command config)
    I do /citizens reload. Sentry ghosts into two identical "test" npcs. One with leggings, one without(or both without)
   When I hit one, both their health shows xx/60, and he illegally retaliates
   Hit the other they both show xx/250 and do not retaliate
This bug, as first listed, shows up after my next server /reload to try to clear the ghost(which does not clear)It spams as long as i am in view range of the two. so i usually tp away, remove the sentry, then /stop and fully reload
http://issues.citizensnpcs.co/browse/CITIZENS-778

**Comment by BriannaThorez** [comment]
Citizens 1094 seems to have corrected this issue some how!

**Comment by mcmonkey4eva** [comment]
@tronman2020 - yup! Fully made 1094 specifically to fix the NPC's not updating issue we've all been having.
