### ISSUE TITLE
NPE on player Death

### ISSUE THREAD

**Issue by ctark** [jrbudda/Sentry#20]
21:21:04 [SEVERE] Could not pass event EntityDamageByEntityEvent to Sentry
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:332)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:80)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:364)
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:386)
        at net.minecraft.server.EntityLiving.damageEntity(EntityLiving.java:591)
        at net.minecraft.server.EntityHuman.damageEntity(EntityHuman.java:595)
        at net.minecraft.server.EntityPlayer.damageEntity(EntityPlayer.java:349)
        at net.minecraft.server.EntityHuman.attack(EntityHuman.java:762)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1020)
        at net.minecraft.server.Packet7UseEntity.handle(SourceFile:36)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:281)
        at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
        at org.getspout.spout.SpoutNetServerHandler.d(SpoutNetServerHandler.java:173)
        at net.minecraft.server.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:583)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:476)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
        at net.aufdemrand.sentry.SentryInstance.die(SentryInstance.java:1094)
        at net.aufdemrand.sentry.SentryInstance.onDamage(SentryInstance.java:1053)
        at net.aufdemrand.sentry.SentryListener.onDamage(SentryListener.java:148)
        at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:330)
        ... 22 more

Not a huge deal, but thought you should know about it non the less!

**Comment by jrbudda** [comment]
hmm, are you by chance using -1 respawn time?

**Comment by jrbudda** [comment]
I think this is fixed
