### ISSUE TITLE
Cannot set npc as sentry...

### ISSUE THREAD

**Issue by Fireant456** [jrbudda/Sentry#203]
here is the error log...
16.04 17:53:11 [Server] WARN ... 28 more
16.04 17:53:11 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
16.04 17:53:11 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
16.04 17:53:11 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
16.04 17:53:11 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
16.04 17:53:11 [Server] WARN Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R1.Packet
16.04 17:53:11 [Server] WARN at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
16.04 17:53:11 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469)
16.04 17:53:11 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558)
16.04 17:53:11 [Server] WARN at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260)
16.04 17:53:11 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:667)
16.04 17:53:11 [Server] WARN at net.minecraft.server.v1_7_R3.ServerConnection.c(SourceFile:134)
16.04 17:53:11 [Server] WARN at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:148)
16.04 17:53:11 [Server] WARN at net.minecraft.server.v1_7_R3.PacketPlayInChat.handle(PacketPlayInChat.java:47)
16.04 17:53:11 [Server] WARN at net.minecraft.server.v1_7_R3.PacketPlayInChat.a(PacketPlayInChat.java:28)
16.04 17:53:11 [Server] WARN at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:815)
16.04 17:53:11 [Server] WARN at net.minecraft.server.v1_7_R3.PlayerConnection.handleCommand(PlayerConnection.java:953)
16.04 17:53:11 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:696)
16.04 17:53:11 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180)
16.04 17:53:11 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
16.04 17:53:11 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
16.04 17:53:11 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:177)
16.04 17:53:11 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
16.04 17:53:11 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:153)
16.04 17:53:11 [Server] WARN at java.lang.reflect.Method.invoke(Unknown Source)
16.04 17:53:11 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
16.04 17:53:11 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
16.04 17:53:11 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16.04 17:53:11 [Server] WARN at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:152)
16.04 17:53:11 [Server] WARN at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:59)
16.04 17:53:11 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:90)
16.04 17:53:11 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:111)
16.04 17:53:11 [Server] WARN at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:114)
16.04 17:53:11 [Server] WARN at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:132)
16.04 17:53:11 [Server] WARN java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R1/Packet

I am running the latest dev of both bukkit and sentry...

**Comment by mcmonkey4eva** [comment]
You are running the latest dev version of Bukkit (1.7.8)
and NOT the latest dev version of Sentry - you're running Sentry for 1.7.2

You can get the latest dev build of Sentry for v1.7.8 here: http://ci.citizensnpcs.co/job/Sentry/
