### ISSUE TITLE
Error when typing /trait sentry (All dev builds as of today are updated)

### ISSUE THREAD

**Issue by JordanFromIT** [jrbudda/Sentry#211]
This is error in console:
[00:55:44 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R4/World
[00:55:44 WARN]:        at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:134)
[00:55:44 WARN]:        at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:116)
[00:55:44 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:111)
[00:55:44 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:90)
[00:55:44 WARN]:        at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:59)
[00:55:44 WARN]:        at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:152)
[00:55:44 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:55:44 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:55:44 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:55:44 WARN]:        at java.lang.reflect.Method.invoke(Method.java:483)
[00:55:44 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:153)
[00:55:44 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[00:55:44 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:177)
[00:55:44 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[00:55:44 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:55:44 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180)
[00:55:44 WARN]:        at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:769)
[00:55:44 WARN]:        at net.minecraft.server.v1_7_R3.PlayerConnection.handleCommand(PlayerConnection.java:1007)
[00:55:44 WARN]:        at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:838)
[00:55:44 WARN]:        at net.minecraft.server.v1_7_R3.PacketPlayInChat.a(PacketPlayInChat.java:28)
[00:55:44 WARN]:        at net.minecraft.server.v1_7_R3.PacketPlayInChat.handle(PacketPlayInChat.java:65)
[00:55:44 WARN]:        at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184)
[00:55:44 WARN]:        at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81)
[00:55:44 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:720)
[00:55:44 WARN]:        at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:283)
[00:55:44 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:583)
[00:55:44 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:489)
[00:55:44 WARN]:        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
[00:55:44 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R4.World
[00:55:44 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
[00:55:44 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
[00:55:44 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[00:55:44 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[00:55:44 WARN]:        ... 28 more

**Comment by mcmonkey4eva** [comment]
@rockxz2135 - You forgot to update to the latest CraftBukkit dev build. You're running CB 1.7.9 with 1.7.10 plugins.
