### ISSUE TITLE
Denizen can't handle npc death event

### ISSUE THREAD

**Issue by MCreation** [jrbudda/Sentry#215]
I use Sentry with Denizen (both have latest version) and trying to handle npc death event for set respawn time for sentry npcs (because /sentry respawn and /npc respawn command didn't work), but have this error and no script execute:

Could not pass event EntityDamageByEntityEvent to Sentry v1.8.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[spigot.jar:git-Spigot-1529]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1529]
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[spigot.jar:git-Spigot-1529]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1529]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1529]
        at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:109) [spigot.jar:git-Spigot-1529]
        at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:550) [spigot.jar:git-Spigot-1529]
        at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:463) [spigot.jar:git-Spigot-1529]
        at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:572) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.EntityLiving.d(EntityLiving.java:1007) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.EntityHuman.d(EntityHuman.java:810) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.EntityLiving.damageEntity(EntityLiving.java:681) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.EntityHuman.damageEntity(EntityHuman.java:751) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.EntityPlayer.damageEntity(EntityPlayer.java:486) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.EntityHuman.attack(EntityHuman.java:936) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:1167) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.PacketPlayInUseEntity.a(SourceFile:55) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.PacketPlayInUseEntity.handle(SourceFile:10) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:720) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:283) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:583) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:489) [spigot.jar:git-Spigot-1529]
        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1529]
Caused by: java.lang.NoSuchMethodError: net.aufdemrand.denizen.objects.dNPC.action(Ljava/lang/String;Lnet/aufdemrand/denizen/objects/dPlayer;)V
        at net.aufdemrand.sentry.DenizenHook.DenizenAction(DenizenHook.java:70) ~[?:?]
        at net.aufdemrand.sentry.SentryInstance.die(SentryInstance.java:491) ~[?:?]
        at net.aufdemrand.sentry.SentryInstance.onDamage(SentryInstance.java:1238) ~[?:?]
        at net.aufdemrand.sentry.SentryListener.onDamage(SentryListener.java:270) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor489.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_60]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_60]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[spigot.jar:git-Spigot-1529]
        ... 24 more

**Comment by mcmonkey4eva** [comment]
Solution: Lie less.
`I use Sentry with Denizen (both have latest version)`
You're running really old versions. And you're running them on 1.7.9
The error is a version incompatibility issue, update to latest or at least latest 1.7.9 versions.

**Comment by MCreation** [comment]
I'm not lie. I use latest versions from dev.bukkit plugins pages: Denizen 0.9.4 and Sentry 1.8.2

**Comment by mcmonkey4eva** [comment]
Denizen latest builds: http://ci.citizensnpcs.co/job/Denizen/
Sentry latest builds: http://ci.citizensnpcs.co/job/Sentry/ or http://wiki.citizensnpcs.co/Sentry#Updates
BukkitDev makes it impossible to keep up-to-date.

**Comment by MCreation** [comment]
Ok, thanks
