### ISSUE TITLE
Error on Die NPC

### ISSUE THREAD

**Issue by ULiX80** [jrbudda/Sentry#218]
[14:34:13 ERROR]: Could not pass event EntityDamageByEntityEvent to Sentry v1.8.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:98) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:386) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:413) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.EntityLiving.damageEntity(EntityLiving.java:656) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.EntityHuman.damageEntity(EntityHuman.java:746) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.EntityPlayer.damageEntity(EntityPlayer.java:452) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.EntityMonster.n(EntityMonster.java:100) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.EntityZombie.n(EntityZombie.java:232) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.PathfinderGoalMeleeAttack.e(PathfinderGoalMeleeAttack.java:100) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.PathfinderGoalSelector.a(PathfinderGoalSelector.java:108) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.EntityInsentient.bm(EntityInsentient.java:427) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.EntityLiving.e(EntityLiving.java:1441) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.EntityInsentient.e(EntityInsentient.java:306) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.EntityMonster.e(EntityMonster.java:21) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.EntityZombie.e(EntityZombie.java:160) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.EntityLiving.h(EntityLiving.java:1304) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.EntityInsentient.h(EntityInsentient.java:150) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.EntityMonster.h(EntityMonster.java:25) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.EntityZombie.h(EntityZombie.java:228) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.World.entityJoinedWorld(World.java:1331) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.World.playerJoinedWorld(World.java:1312) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.World.tickEntities(World.java:1200) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.WorldServer.tickEntities(WorldServer.java:481) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:649) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [CB.jar:git-Bukkit-1.7.2-R0.3-56-g3779cff-b3072jnks]
Caused by: java.lang.NoSuchMethodError: net.aufdemrand.denizen.objects.dNPC.action(Ljava/lang/String;Lnet/aufdemrand/denizen/objects/dPlayer;)V

**Comment by mcmonkey4eva** [comment]
http://wiki.citizensnpcs.co/Sentry#Updates
Update to 1.8.2 build#2, it's a micro-patch for exactly this error.

**Comment by ULiX80** [comment]
10x
this has helped
