### ISSUE TITLE
some errors with death events

### ISSUE THREAD

**Issue by madtomic** [jrbudda/Sentry#220]
some errors

10:56:37 PM [22:56:37 ERROR]: Could not pass event EntityDamageByEntityEvent to Sentry v1.8.2
10:56:37 PM org.bukkit.event.EventException
10:56:37 PM at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:98) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:407) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:434) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at net.minecraft.server.v1_7_R3.EntityLiving.damageEntity(EntityLiving.java:658) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at net.minecraft.server.v1_7_R3.EntityHuman.damageEntity(EntityHuman.java:746) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at net.minecraft.server.v1_7_R3.EntityPlayer.damageEntity(EntityPlayer.java:452) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at net.minecraft.server.v1_7_R3.EntityHuman.attack(EntityHuman.java:925) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:1106) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at net.minecraft.server.v1_7_R3.PacketPlayInUseEntity.a(SourceFile:55) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at net.minecraft.server.v1_7_R3.PacketPlayInUseEntity.handle(SourceFile:10) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:157) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at net.minecraft.server.v1_7_R3.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:37 PM at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:38 PM at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:38 PM at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:38 PM at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:38 PM Caused by: java.lang.NoSuchMethodError: net.aufdemrand.denizen.objects.dNPC.action(Ljava/lang/String;Lnet/aufdemrand/denizen/objects/dPlayer;)V
10:56:38 PM at net.aufdemrand.sentry.DenizenHook.DenizenAction(DenizenHook.java:70) ~[?:?]
10:56:38 PM at net.aufdemrand.sentry.SentryInstance.die(SentryInstance.java:491) ~[?:?]
10:56:38 PM at net.aufdemrand.sentry.SentryInstance.onDamage(SentryInstance.java:1238) ~[?:?]
10:56:38 PM at net.aufdemrand.sentry.SentryListener.onDamage(SentryListener.java:270) ~[?:?]
10:56:38 PM at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source) ~[?:?]
10:56:38 PM at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
10:56:38 PM at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
10:56:38 PM at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
10:56:38 PM ... 20 more

**Comment by mcmonkey4eva** [comment]
It looks like you need to update Denizen to the latest 0.9.4 build. http://wiki.citizensnpcs.co/Versions
