### ISSUE TITLE
sentry don't respawn 

### ISSUE THREAD

**Issue by jammylow3** [jrbudda/Sentry#234]
hello hope you can help i have both latest of cit and sentry but when i kill a sentry they dont respawn i put on 1 sec 10 sec and 15 secs but they never come bk in less i do manual

**Comment by Matterom** [comment]
What is your version of citizens-Bukkit/Spigot

**Comment by jammylow3** [comment]
cit is 2.0.14

**Comment by jammylow3** [comment]
sentry is the latest one on http://ci.citizensnpcs.co/job/Sentry/

**Comment by Matterom** [comment]
What about server software

**Comment by jammylow3** [comment]
i use spigot
logmein  hamachi

**Comment by jammylow3** [comment]
#Sentry configuration

#Server-wide options for Sentry
Server:
 #If true Sentries will die like normal mobs, instead of being despawned. Player-type Sentry deaths will be announced in chat.
 DieLikePlayers: true
 #The amount of EXP sentries drop. Only works if Drops is turned on.
 ExpValue: 5
 #This is how often, in ticks, the Sentry performs his interal logic looking for targets, etc. Increasing this value may lighten server load, 
 #but will decrease Sentries responsiveness and maximum rate of fire.
 LogicTicks: 10
 #Whether or not Sentries in bodyguard mode always deal damage regardless of other protection plugins.
 BodyguardsObeyProtection: true
 #Whether or not Sentries are immune to damage from entites on their ignore list. Immunity to damage also prevents retaliation.
 IgnoreListInvincibility: true

#Default stats for new Sentries
DefaultStats:
 Strength: 1
 Armor: 0
 Speed: 1.0
 Health: 20
 AttackRate: 2.0
 HealRate: 0.0
 NightVision: 16
 Range: 10
 WarningRange: 0
 Respawn: 20
 FollowDistance: 4

#Default options for new Sentries
DefaultOptions:
 Drops: false
 KillDrops: true
 Criticals: true
 Invincible: false
 Retaliate: true
 FriendlyFire: false
 Targetable: true

#Default texts for new Sentries. You can use <NPC> and <PLAYER> as placeholders.
DefaultTexts:
 Warning: "&c<NPC> says Halt! Come no closer!"
 Greeting: "&a<NPC> says Welcome, <PLAYER>"

#Default target list for new Sentries. 
DefaultTargets:
 #- "entity:monster"

#Default ignore list for new Sentries
DefaultIgnores:
 #- "entity:owner"

#Configurable messages used by all Sentries. You can use <NPC>, <PLAYER>, <ITEM>, and <AMOUNT> as placeholders. Remove a message or set it to "" to prevent it from displaying at all.
GlobalTexts:
 Miss: "&7**\* You MISS <NPC>."
 Hit: "&f**\* You hit <NPC> for <AMOUNT> damage."
 Crit1: "&e**\* You injure <NPC> for <AMOUNT> damage."
 Crit2: "&6**\* You MAIM <NPC> with your <ITEM> for <AMOUNT> damage."
 Crit3: "&c**\* You DISEMBOWEL <NPC> with your <ITEM> for <AMOUNT> damage."
 Block: "&7**\* You fail to penetrate <NPC>'s armor."
 Glance: "&7**\* Your blow glances off <NPC> for <AMOUNT> damage."

#These are the percentage chancees of doing a certain damage to a Sentry if Criticals is turned on. Whole numbers only. Remove or Set to 0 to disable a hit type.
HitChances:
 Miss: 4
 Glance: 4
 Crit1: 6
 Crit2: 4
 Crit3: 2

#Set the item used by each type of Sentry. Use item name or id #. 
#Remove an entry to disable that attack type. Any other item makes a Brawler.
AttackTypes:
 Archer: BOW
 Pyro1: REDSTONE_TORCH_ON
 Pyro2: TORCH
 Pyro3: BLAZE_ROD
 Bombardier: EGG
 IceMagi: SNOW_BALL
 StormCaller1: PAPER
 StormCaller2: BOOK
 StormCaller3: BOOK_AND_QUILL
 #Note Witch Doctors need a potion equipped to know what to throw!
 WitchDoctor: POTION
 Warlock1: ENDER_PEARL
 Warlock2: SKULL_ITEM

#The following items will ADD to the sentry's base armor. 
#Decimals are allowed but all minecraft damge is in integers. 
#You would need 2 items of 0.3 Armor buff to add 1 point of armor.
ArmorBuffs:
 #- IRON_HELMET 1.0
 #- DIAMOND_CHESTPLATE 4.0

#The following items will ADD to the sentry's base strength. 
StrengthBuffs:
 #- IRON_SWORD 1
 #- TORCH 5

#The following items will ADD to the sentry's base speed. 
SpeedBuffs:
 #- LEATHER_BOOTS 0.2
 #- IRON_BOOTS -0.1

#Apply potion effects on hit for various weapon types. Multiple effects allowed. 
#Use format: [item name/id] [potion name/id:duration in ticks:level] There are 20 ticks in a second. 
#Duration and Level are optional, default duration is 20, level is 1.
#Valid potion names: 
#speed, slow, fast_digging, slow_digging, increase_damage, heal, harm, jump, confusion, 
#regeneration, damage_resistance, fire_resistance, water_breating, blindness, hunger, weakness, poison
WeaponEffects:
- SNOW_BALL slow:20
  #- GOLD_SWORD poison:60:2 confusion

#The lists below control what items are equipped as armor. These should only be changed to disable specific armors or add extended (i.e. Spout) items.

#The following items will be equipped as helmets, can use name or id #
Helmets:
- PUMPKIN
- JACK_O_LANTERN
- LEATHER_HELMET
- CHAINMAIL_HELMET
- GOLD_HELMET
- IRON_HELMET
- DIAMOND_HELMET

#The following items will be equipped as chestplates, can use name or id #.
Chestplates:
    - LEATHER_CHESTPLATE
    - CHAINMAIL_CHESTPLATE
    - GOLD_CHESTPLATE
    - IRON_CHESTPLATE
    - DIAMOND_CHESTPLATE

#The following items will be equipped as leggings, can use name or id #
Leggings:
    - LEATHER_LEGGINGS
    - CHAINMAIL_LEGGINGS
    - GOLD_LEGGINGS
    - IRON_LEGGINGS
    - DIAMOND_LEGGINGS

#The following items will be equipped as boots, can use name or id #
Boots:  
    - LEATHER_BOOTS
    - CHAINMAIL_BOOTS
    - GOLD_BOOTS
    - IRON_BOOTS
    - DIAMOND_BOOTS

**Comment by jammylow3** [comment]
# Citizens Configuration

npc:
  chat:
    options:
      bystanders-hear-targeted-chat: true
      max-number-of-targets-to-show: 2
      multiple-targets-format: <target>|, <target>| & <target>| & others
      range: 5
      max-text-range: 500
    format:
      no-targets: '[<npc>]: <text>'
      with-target-to-bystanders: '[<npc>] -> [<target>]: <text>'
      to-target: '[<npc>] -> You: <text>'
      with-targets-to-bystanders: '[<npc>] -> [<targets>]: <text>'
  default:
    look-close:
      enabled: false
      range: 5
    pathfinding:
      range: 25.0
    random-talker: true
    realistic-looking: false
    stationary-ticks: -1
    talk-close:
      enabled: false
      range: 5
    text:
      '0': Hi, I'm <npc>!
  limits:
    default-limit: 10
    max-permission-checks: 100
    max-speed: 100
  chunks:
    always-keep-loaded: false
  skins:
    max-retries: -1
    retry-delay: 120
  pathfinding:
    new-finder-open-doors: false
    attack-range: 3.0625
    use-new-finder: false
  packets:
    update-delay: 30
  selection:
    quick-select: false
    item: '280'
    message: <b>You selected <a><npc><b>!
  player:
    remove-from-list: true
  server-ownership: false
  text:
    max-talk-cooldown: 5
    min-talk-cooldown: 10
    talk-item: '340'
  controllable:
    use-boat-controls: true
advanced:
  check-minecraft-version: true
storage:
  database:
    driver: ''
    password: ''
    url: ''
    username: ''
  save-task:
    delay: 72000
  file: saves.yml
  type: yaml
general:
  debug-mode: false
  debug-pathfinding: false
  color-scheme:
    message-highlight: <e>
    message: <a>
  translation:
    locale: ''
economy:
  npc:
    cost: 100.0
subplugins:
  folder: plugins

**Comment by jammylow3** [comment]
[01:33:47 INFO]: Cactus Growth Modifier: 100%
[01:33:47 INFO]: Cane Growth Modifier: 100%
[01:33:47 INFO]: Melon Growth Modifier: 100%
[01:33:47 INFO]: Mushroom Growth Modifier: 100%
[01:33:47 INFO]: Pumpkin Growth Modifier: 100%
[01:33:47 INFO]: Sapling Growth Modifier: 100%
[01:33:47 INFO]: Wheat Growth Modifier: 100%
[01:33:47 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[01:33:47 INFO]: Max TNT Explosions: 100
[01:33:47 INFO]: Sending up to 5 chunks per packet
[01:33:47 INFO]: Random Lighting Updates: false
[01:33:47 INFO]: Structure Info Saving: true
[01:33:47 INFO]: -------- World Settings For [world_nether] --------
[01:33:47 INFO]: View Distance: 10
[01:33:47 INFO]: Item Despawn Rate: 6000
[01:33:47 INFO]: Item Merge Radius: 2.5
[01:33:47 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[01:33:47 INFO]: Arrow Despawn Rate: 1200
[01:33:47 INFO]: Zombie Aggressive Towards Villager: true
[01:33:47 INFO]: Experience Merge Radius: 3.0
[01:33:47 INFO]: Chunks to Grow per Tick: 650
[01:33:47 INFO]: Clear tick list: false
[01:33:47 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[01:33:47 INFO]: Max Entity Collisions: 8
[01:33:47 INFO]: Anti X-Ray: true
[01:33:47 INFO]:        Engine Mode: 1
[01:33:47 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74,
82, 129, 130]
[01:33:47 INFO]:        Replace Blocks: [1, 5]
[01:33:47 INFO]: Alternative Hopper Ticking: false
[01:33:47 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[01:33:47 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[01:33:47 INFO]: Nerfing mobs spawned from spawners: false
[01:33:47 INFO]: Mob Spawn Range: 4
[01:33:47 INFO]: Cactus Growth Modifier: 100%
[01:33:47 INFO]: Cane Growth Modifier: 100%
[01:33:47 INFO]: Melon Growth Modifier: 100%
[01:33:47 INFO]: Mushroom Growth Modifier: 100%
[01:33:47 INFO]: Pumpkin Growth Modifier: 100%
[01:33:47 INFO]: Sapling Growth Modifier: 100%
[01:33:47 INFO]: Wheat Growth Modifier: 100%
[01:33:47 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[01:33:47 INFO]: Max TNT Explosions: 100
[01:33:47 INFO]: Sending up to 5 chunks per packet
[01:33:47 INFO]: Random Lighting Updates: false
[01:33:47 INFO]: Structure Info Saving: true
[01:33:47 INFO]: -------- World Settings For [world_the_end] --------
[01:33:47 INFO]: View Distance: 10
[01:33:47 INFO]: Item Despawn Rate: 6000
[01:33:47 INFO]: Item Merge Radius: 2.5
[01:33:47 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[01:33:47 INFO]: Arrow Despawn Rate: 1200
[01:33:47 INFO]: Zombie Aggressive Towards Villager: true
[01:33:47 INFO]: Experience Merge Radius: 3.0
[01:33:47 INFO]: Chunks to Grow per Tick: 650
[01:33:47 INFO]: Clear tick list: false
[01:33:47 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[01:33:47 INFO]: Max Entity Collisions: 8
[01:33:47 INFO]: Anti X-Ray: true
[01:33:47 INFO]:        Engine Mode: 1
[01:33:47 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74,
82, 129, 130]
[01:33:47 INFO]:        Replace Blocks: [1, 5]
[01:33:47 INFO]: Alternative Hopper Ticking: false
[01:33:47 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[01:33:47 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[01:33:47 INFO]: Nerfing mobs spawned from spawners: false
[01:33:47 INFO]: Mob Spawn Range: 4
[01:33:47 INFO]: Cactus Growth Modifier: 100%
[01:33:47 INFO]: Cane Growth Modifier: 100%
[01:33:47 INFO]: Melon Growth Modifier: 100%
[01:33:47 INFO]: Mushroom Growth Modifier: 100%
[01:33:47 INFO]: Pumpkin Growth Modifier: 100%
[01:33:47 INFO]: Sapling Growth Modifier: 100%
[01:33:47 INFO]: Wheat Growth Modifier: 100%
[01:33:47 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[01:33:47 INFO]: Max TNT Explosions: 100
[01:33:47 INFO]: Sending up to 5 chunks per packet
[01:33:47 INFO]: Random Lighting Updates: false
[01:33:47 INFO]: Structure Info Saving: true
[01:33:47 INFO]: Preparing start region for level 0 (Seed: 5350418096430930869)
[01:33:48 INFO]: Preparing spawn area: 55%
[01:33:49 INFO]: Preparing start region for level 1 (Seed: 4489678980065516093)
[01:33:50 INFO]: Preparing spawn area: 69%
[01:33:50 INFO]: Preparing start region for level 2 (Seed: 4489678980065516093)
[01:33:50 INFO]: [WorldEdit] Enabling WorldEdit v5.6.3
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): WEPIF: Using the Bukkit Permissions API.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [Essentials] Enabling Essentials vTeamCity
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): Bukkit version format changed. Version not checked.

[01:33:51 INFO](1.8-R0.1-SNAPSHOT): Using locale en_US
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): Using locale en_US
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [Vault][Economy] Essentials Economy hooked.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): Essentials: Using config file enhanced permissions.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): Permissions listed in as player-commands will be given to all u
sers.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [EssentialsProtect] Enabling EssentialsProtect vTeamCity
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [LoginSecurity] Enabling LoginSecurity v2.0.7
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [EssentialsChat] Enabling EssentialsChat vTeamCity
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [ClearLag] Enabling ClearLag v2.7.7
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [ClearLag] Loading modules...
[01:33:51 WARN]: [ClearLag] mob-range requires you to use bukkit v1.7_r4 (1.7.10
)
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [ClearLag] Modules have been loaded!
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [ClearLag] Clearlag is now enabled!
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [ClearLag] Checking for updates...
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [PermissionsEx] Enabling PermissionsEx v1.20.4
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): WEPIF: PermissionsEx detected! Using PermissionsEx for permissi
ons.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [Vault][Permission] PermissionsEx hooked.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [Vault][Chat] PermissionsEx_Chat hooked.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): Essentials: Using PermissionsEx based permissions.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [Simple-AutoSave] Enabling Simple-AutoSave v0.2.2
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [Simple-AutoSave] [Simple-AutoSave] 0.2.2 enabled.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [Simple-AutoSave] Autosave Started.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [EssentialsSpawn] Enabling EssentialsSpawn vTeamCity
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard] Enabling WorldGuard v6.0.0-beta-05.1569-
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard](world) TNT ignition is PERMITTED.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard](world) Lighters are PERMITTED.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard](world) Lava fire is blocked.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard](world) Fire spread is UNRESTRICTED.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard] Loaded configuration for world 'world'
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard](world_nether) TNT ignition is PERMITTED.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard](world_nether) Lighters are PERMITTED.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard](world_nether) Lava fire is blocked.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard](world_nether) Fire spread is UNRESTRICTED.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard] Loaded configuration for world 'world_nether'
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard](world_the_end) TNT ignition is PERMITTED.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard](world_the_end) Lighters are PERMITTED.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard](world_the_end) Lava fire is blocked.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard](world_the_end) Fire spread is UNRESTRICTED.
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard] Loaded configuration for world 'world_the_end'
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [WorldGuard] Loading region data...
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): UUID of player foundo is 1a113a4d-caba-49e3-977d-085e5976ca70
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [ClearLag] No updates found!
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): [Citizens] Enabling Citizens v2.0.14-SNAPSHOT (build 1208)
[01:33:51 INFO](1.8-R0.1-SNAPSHOT): Creating file: config.yml
[01:33:52 ERROR]: [Citizens] Unable to find Rhino classes - javascript scripts w
on't see non-CraftBukkit classes
[01:33:52 INFO](Done): Creating file: saves.yml
[01:33:52 INFO](Done): [Sentry] Enabling Sentry v1.8.4
[01:33:52 INFO](Done): [Sentry] Could not register with Denizen
[01:33:52 INFO](Done): [Sentry] Could not find or register with Towny
[01:33:52 INFO](Done): [Sentry] Could not find or register with Factions.
[01:33:52 INFO](Done): [Sentry] Could not find or register with War.
[01:33:52 INFO](Done): [Sentry] Could not find or register with SimpleClans.
[01:33:52 INFO](Done): Server permissions file permissions.yml is empty, ignoring it

[01:33:52 INFO](Done): [Citizens] Loaded 0 NPCs.
[01:33:52 INFO](Done): [Vault] Checking for Updates ...
[01:33:52 INFO](Done): [Vault] No new version available
[01:34:01 INFO]: foundo[/25.65.154.170:59096] logged in with entity id 129 at ([
world] 375.3606609120811, 64.0, 998.3348017182656)
[01:34:05 INFO]: foundo issued server command: /login 123
[01:34:05 INFO]: [LoginSecurity] foundo authenticated
[01:34:16 INFO]: foundo issued server command: /npc create alfie
[01:34:23 INFO]: foundo issued server command: /trait sentry
[01:34:23 WARN]: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionM
anager.getGroupList()Ljava/util/List;
[01:34:23 WARN]:        at net.milkbowl.vault.permission.plugins.Permission_Perm
issionsEx.getGroups(Permission_PermissionsEx.java:372)
[01:34:23 WARN]:        at net.aufdemrand.sentry.Sentry.doGroups(Sentry.java:123
)
[01:34:23 WARN]:        at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait
.java:126)
[01:34:23 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(Abstrac
tNPC.java:109)
[01:34:23 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(Abstrac
tNPC.java:88)
[01:34:23 WARN]:        at net.citizensnpcs.commands.TraitCommands.addTrait(Trai
tCommands.java:59)
[01:34:23 WARN]:        at net.citizensnpcs.commands.TraitCommands.toggle(TraitC
ommands.java:152)
[01:34:23 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[01:34:23 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[01:34:23 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[01:34:23 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[01:34:23 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMe
thod(CommandManager.java:154)
[01:34:23 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(C
ommandManager.java:90)
[01:34:23 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSa
fe(CommandManager.java:178)
[01:34:23 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236
)
[01:34:23 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
[01:34:23 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:141)
[01:34:23 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCo
mmand(CraftServer.java:646)
[01:34:23 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.handleC
ommand(PlayerConnection.java:1115)
[01:34:23 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.a(Playe
rConnection.java:950)
[01:34:23 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(Packe
tPlayInChat.java:26)
[01:34:23 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(Packe
tPlayInChat.java:53)
[01:34:23 WARN]:        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(Sou
rceFile:13)
[01:34:23 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[01:34:23 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[01:34:23 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(Minecr
aftServer.java:696)
[01:34:23 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(Dedica
tedServer.java:316)
[01:34:23 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(Minecr
aftServer.java:634)
[01:34:23 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(Mine
craftServer.java:537)
[01:34:23 WARN]:        at java.lang.Thread.run(Unknown Source)
[01:34:54 INFO]: foundo issued server command: /sentry spawn
[01:35:01 INFO]: [we care] Saving Worlds & Player Data...
[01:35:01 WARN]: A manual (plugin-induced) save has been detected while server i
s configured to auto-save. This may affect performance.
[01:35:13 INFO]: foundo issued server command: /sentry respawn 20
[01:35:35 INFO]: foundo issued server command: /sentry equip 275
[01:35:48 INFO]: foundo issued server command: /sentry equip
[01:36:01 INFO]: [we care] Saving Worlds & Player Data...
[01:36:06 INFO]: foundo issued server command: /sentry path
[01:36:10 INFO]: foundo issued server command: /npc path
[01:36:12 WARN]: [WorldEdit] No compatible nms block class found.
[01:36:27 INFO]: foundo issued server command: /day
[01:37:01 INFO]: [we care] Saving Worlds & Player Data...
[01:37:04 INFO]: foundo issued server command: /sentry target add entity:all
[01:37:14 INFO]: foundo issued server command: /npc path
[01:37:29 INFO]: foundo issued server command: /gamemode 1
[01:37:34 INFO]: foundo issued server command: /gamemode 0
[01:38:01 INFO]: [we care] Saving Worlds & Player Data...
[01:38:36 INFO]: foundo issued server command: /sentry spawn
[01:38:45 INFO]: foundo issued server command: /npc spawn
[01:38:45 ERROR]: [Citizens] An exception occurred while the trait sentry was sp
awning for NPC ID 0.
[01:38:45 WARN]: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionM
anager.getGroupList()Ljava/util/List;
[01:38:45 WARN]:        at net.milkbowl.vault.permission.plugins.Permission_Perm
issionsEx.getGroups(Permission_PermissionsEx.java:372)
[01:38:45 WARN]:        at net.aufdemrand.sentry.Sentry.doGroups(Sentry.java:123
)
[01:38:45 WARN]:        at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait
.java:126)
[01:38:45 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.ja
va:205)
[01:38:45 WARN]:        at net.citizensnpcs.commands.NPCCommands$5.run(NPCComman
ds.java:1361)
[01:38:45 WARN]:        at net.citizensnpcs.commands.NPCCommands.spawn(NPCComman
ds.java:1370)
[01:38:45 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[01:38:45 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[01:38:45 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[01:38:45 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[01:38:45 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMe
thod(CommandManager.java:154)
[01:38:45 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(C
ommandManager.java:90)
[01:38:45 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSa
fe(CommandManager.java:178)
[01:38:45 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236
)
[01:38:45 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
[01:38:45 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:141)
[01:38:45 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCo
mmand(CraftServer.java:646)
[01:38:45 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.handleC
ommand(PlayerConnection.java:1115)
[01:38:45 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.a(Playe
rConnection.java:950)
[01:38:45 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(Packe
tPlayInChat.java:26)
[01:38:45 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(Packe
tPlayInChat.java:53)
[01:38:45 WARN]:        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(Sou
rceFile:13)
[01:38:45 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[01:38:45 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[01:38:45 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(Minecr
aftServer.java:696)
[01:38:45 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(Dedica
tedServer.java:316)
[01:38:45 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(Minecr
aftServer.java:634)
[01:38:45 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(Mine
craftServer.java:537)
[01:38:45 WARN]:        at java.lang.Thread.run(Unknown Source)
[01:39:01 INFO]: [we care] Saving Worlds & Player Data...

**Comment by mcmonkey4eva** [comment]
Update PEX and Vault.

**Comment by jammylow3** [comment]
works great and fixed a few more problems at same time thank you for fast reply :) 
and thanks you for your help you been great
