### ISSUE TITLE
error when loading up sentry.

### ISSUE THREAD

**Issue by ghost** [jrbudda/Sentry#246]
[17:42:49 ERROR]: [Citizens] An exception occurred while the trait sentry was spawning for NPC ID 32.
[17:42:49 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R2/World
[17:42:49 WARN]:        at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:134)
[17:42:49 WARN]:        at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:116)
[17:42:49 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:205)
[17:42:49 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:423)
[17:42:49 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:395)
[17:42:49 WARN]:        at net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:109)
[17:42:49 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:42:49 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:42:49 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:42:49 WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[17:42:49 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[17:42:49 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:42:49 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[17:42:49 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[17:42:49 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:50)
[17:42:49 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[17:42:49 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
[17:42:49 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347)
[17:42:49 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:34)
[17:42:49 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:720)
[17:42:49 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[17:42:49 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[17:42:49 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[17:42:49 WARN]:        at java.lang.Thread.run(Thread.java:745)
[17:42:49 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R2.World
[17:42:49 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[17:42:49 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[17:42:49 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:42:49 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:42:49 WARN]:        ... 24 more

**Comment by mcmonkey4eva** [comment]
Wrong version of Sentry. Get correct version here: http://wiki.citizensnpcs.co/Sentry#Updates
