### ISSUE TITLE
Sentry Error + Won't fight anything

### ISSUE THREAD

**Issue by stewpyid** [jrbudda/Sentry#247]
Sentrys work to an extent but they won't fight anything (even when I adjust their targets to me) at all and when equipped with something, I have to rejoin the server to see the weapon physically on them.
When I add the trait sentry, I do get an error: 

[14:37:41 ERROR]: [Citizens] An exception occurred while the trait sentry was sp
awning for NPC ID 20.
[14:37:41 WARN]: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionM
anager.getGroupList()Ljava/util/List;
[14:37:41 WARN]:        at net.milkbowl.vault.permission.plugins.Permission_Perm
issionsEx.getGroups(Permission_PermissionsEx.java:372)
[14:37:41 WARN]:        at net.aufdemrand.sentry.Sentry.doGroups(Sentry.java:123
)
[14:37:41 WARN]:        at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait
.java:126)
[14:37:41 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.ja
va:229)
[14:37:41 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:4
44)
[14:37:41 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(Even
tListen.java:399)
[14:37:41 WARN]:        at net.citizensnpcs.EventListen.onChunkLoad(EventListen.
java:116)
[14:37:41 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[14:37:41 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[14:37:41 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[14:37:41 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[14:37:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(Jav
aPluginLoader.java:306)
[14:37:41 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(Regist
eredListener.java:62)
[14:37:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(Simpl
ePluginManager.java:502)
[14:37:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(Simpl
ePluginManager.java:487)
[14:37:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvide
r.callStage2(ChunkIOProvider.java:59)
[14:37:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvide
r.callStage2(ChunkIOProvider.java:1)
[14:37:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecu
tor$Task.finish(AsynchronousExecutor.java:188)
[14:37:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecu
tor$Task.get(AsynchronousExecutor.java:164)
[14:37:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecu
tor.skipQueue(AsynchronousExecutor.java:334)
[14:37:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecu
tor.getSkipQueue(AsynchronousExecutor.java:295)
[14:37:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecuto
r.syncChunkLoad(ChunkIOExecutor.java:16)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getC
hunkAt(ChunkProviderServer.java:115)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getC
hunkAt(ChunkProviderServer.java:97)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.
java:256)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(
PlayerList.java:330)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.
java:156)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginLis
tener.java:144)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginLis
tener.java:54)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.a(Network
Manager.java:231)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.ServerConnection.c(Serve
rConnection.java:148)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(Minecr
aftServer.java:817)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(Dedica
tedServer.java:367)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(Minecr
aftServer.java:657)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(Mine
craftServer.java:560)
[14:37:41 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:37:41 INFO]: Bluppity[/99.23.5.68:64317] logged in with entity id 249 at ([w
orld]-81.15947566588457, 67.0, 492.7047941414426)
[14:37:41 ERROR]: [Citizens] An exception occurred while the trait sentry was sp
awning for NPC ID 19.
[14:37:41 WARN]: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionM
anager.getGroupList()Ljava/util/List;
[14:37:41 WARN]:        at net.milkbowl.vault.permission.plugins.Permission_Perm
issionsEx.getGroups(Permission_PermissionsEx.java:372)
[14:37:41 WARN]:        at net.aufdemrand.sentry.Sentry.doGroups(Sentry.java:123
)
[14:37:41 WARN]:        at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait
.java:126)
[14:37:41 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.ja
va:229)
[14:37:41 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:4
44)
[14:37:41 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(Even
tListen.java:399)
[14:37:41 WARN]:        at net.citizensnpcs.EventListen.onChunkLoad(EventListen.
java:116)
[14:37:41 WARN]:        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown
Source)
[14:37:41 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[14:37:41 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[14:37:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(Jav
aPluginLoader.java:306)
[14:37:41 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(Regist
eredListener.java:62)
[14:37:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(Simpl
ePluginManager.java:502)
[14:37:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(Simpl
ePluginManager.java:487)
[14:37:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvide
r.callStage2(ChunkIOProvider.java:59)
[14:37:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvide
r.callStage2(ChunkIOProvider.java:1)
[14:37:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecu
tor$Task.finish(AsynchronousExecutor.java:188)
[14:37:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecu
tor.finishActive(AsynchronousExecutor.java:347)
[14:37:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecuto
r.tick(ChunkIOExecutor.java:34)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(Minecr
aftServer.java:737)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(Dedica
tedServer.java:367)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(Minecr
aftServer.java:657)
[14:37:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(Mine
craftServer.java:560)
[14:37:41 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:37:57 INFO]: Bluppity issued server command: /npc create Katherine --trait s
entry
[14:37:57 WARN]: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionM
anager.getGroupList()Ljava/util/List;
[14:37:57 WARN]:        at net.milkbowl.vault.permission.plugins.Permission_Perm
issionsEx.getGroups(Permission_PermissionsEx.java:372)
[14:37:57 WARN]:        at net.aufdemrand.sentry.Sentry.doGroups(Sentry.java:123
)
[14:37:57 WARN]:        at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait
.java:126)
[14:37:57 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(Abstrac
tNPC.java:109)
[14:37:57 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCComma
nds.java:382)
[14:37:57 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[14:37:57 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[14:37:57 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[14:37:57 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[14:37:57 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMe
thod(CommandManager.java:154)
[14:37:57 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(C
ommandManager.java:90)
[14:37:57 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSa
fe(CommandManager.java:178)
[14:37:57 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236
)
[14:37:57 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
[14:37:57 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:141)
[14:37:57 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCo
mmand(CraftServer.java:642)
[14:37:57 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleC
ommand(PlayerConnection.java:1135)
[14:37:57 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(Playe
rConnection.java:970)
[14:37:57 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(Packe
tPlayInChat.java:45)
[14:37:57 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(Packe
tPlayInChat.java:1)
[14:37:57 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.
run(SourceFile:13)
[14:37:57 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[14:37:57 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:37:57 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtil
s.java:19)
[14:37:57 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(Minecr
aftServer.java:718)
[14:37:57 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(Dedica
tedServer.java:367)
[14:37:57 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(Minecr
aftServer.java:657)
[14:37:57 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(Mine
craftServer.java:560)
[14:37:57 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:37:58 INFO]: joe was slain by Zombie
[14:37:58 ERROR]: [Citizens] An exception occurred while the trait sentry was sp
awning for NPC ID 22.
[14:37:58 WARN]: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionM
anager.getGroupList()Ljava/util/List;
[14:37:58 WARN]:        at net.milkbowl.vault.permission.plugins.Permission_Perm
issionsEx.getGroups(Permission_PermissionsEx.java:372)
[14:37:58 WARN]:        at net.aufdemrand.sentry.Sentry.doGroups(Sentry.java:123
)
[14:37:58 WARN]:        at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait
.java:126)
[14:37:58 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.ja
va:229)
[14:37:58 WARN]:        at net.citizensnpcs.npc.entity.HumanController$SkinFetch
er$1.run(HumanController.java:270)
[14:37:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.ru
n(CraftTask.java:71)
[14:37:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftSchedul
er.mainThreadHeartbeat(CraftScheduler.java:350)
[14:37:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(Minecr
aftServer.java:726)
[14:37:58 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(Dedica
tedServer.java:367)
[14:37:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(Minecr
aftServer.java:657)
[14:37:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(Mine
craftServer.java:560)
[14:37:58 WARN]:        at java.lang.Thread.run(Unknown Source)

I'm not sure if it's because this version is 1.8.6 and I'm on 1.8.7 or something else. I didn't think there would be such a huge change between those two versions so I just assumed it would go well. Guess not. Any help would be greatly appreciated!

**Comment by mcmonkey4eva** [comment]
Update Vault + Your permissions plugin

**Comment by stewpyid** [comment]
Deleting Vault fixed this since I can't update Vault past what it is at the moment. Thank you.
