### ISSUE TITLE
Error: using /trait sentry

### ISSUE THREAD

**Issue by Jadeng47** [jrbudda/Sentry#257]
it came back to me 'please report this error':
[16:36:19 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/Packet
[16:36:19 WARN]:    at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:134)
[16:36:19 WARN]:    at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:116)
[16:36:19 WARN]:    at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:109)
[16:36:19 WARN]:    at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:88)
[16:36:19 WARN]:    at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
[16:36:19 WARN]:    at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
[16:36:19 WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:36:19 WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:36:19 WARN]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:36:19 WARN]:    at java.lang.reflect.Method.invoke(Unknown Source)
[16:36:19 WARN]:    at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[16:36:19 WARN]:    at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[16:36:19 WARN]:    at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[16:36:19 WARN]:    at net.citizensnpcs.Citizens.onCommand(Citizens.java:238)
[16:36:19 WARN]:    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:36:19 WARN]:    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[16:36:19 WARN]:    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620)
[16:36:19 WARN]:    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106)
[16:36:19 WARN]:    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966)
[16:36:19 WARN]:    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37)
[16:36:19 WARN]:    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9)
[16:36:19 WARN]:    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:36:19 WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:36:19 WARN]:    at java.util.concurrent.FutureTask.run(Unknown Source)
[16:36:19 WARN]:    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:36:19 WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673)
[16:36:19 WARN]:    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335)
[16:36:19 WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629)
[16:36:19 WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537)
[16:36:19 WARN]:    at java.lang.Thread.run(Unknown Source)
[16:36:19 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.Packet
[16:36:19 WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
[16:36:19 WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
[16:36:19 WARN]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[16:36:19 WARN]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[16:36:19 WARN]:    ... 30 more

**Comment by mcmonkey4eva** [comment]
Wrong version of Sentry, acquire the correct one here -> http://wiki.citizensnpcs.co/Sentry#Updates

**Comment by Jadeng47** [comment]
Thanks It Worked!
