### ISSUE TITLE
Server Crash Log & Information

### ISSUE THREAD

**Issue by ci29995** [jrbudda/Sentry#26]
craftbukkit 1.3.1-R2.0
What happened?

[SEVERE] java.lang.AbstractMethodError: net.aufdemrand.sentry.BodyguardTeleportStuckAction.run(Lnet/citizensnpcs/api/npc/NPC;Lnet/citizensnpcs/api/ai/Navigator;)V
11:53:02 AM [SEVERE]    at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:145)
11:53:02 AM [SEVERE]    at net.citizensnpcs.npc.ai.CitizensNavigator.update(CitizensNavigator.java:166)
11:53:02 AM [SEVERE]    at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:163)
11:53:02 AM [SEVERE]    at net.citizensnpcs.npc.entity.CitizensHumanNPC.update(CitizensHumanNPC.java:138)
11:53:02 AM [SEVERE]    at net.citizensnpcs.npc.entity.EntityHumanNPC.h_(EntityHumanNPC.java:85)
11:53:02 AM [SEVERE]    at net.minecraft.server.World.entityJoinedWorld(World.java:1245)
11:53:02 AM [SEVERE]    at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:511)
11:53:02 AM [SEVERE]    at net.minecraft.server.World.playerJoinedWorld(World.java:1227)
11:53:02 AM [SEVERE]    at net.minecraft.server.World.tickEntities(World.java:1125)
11:53:02 AM [SEVERE]    at net.minecraft.server.WorldServer.tickEntities(WorldServer.java:428)
11:53:02 AM [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:564)
11:53:02 AM [SEVERE]    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
11:53:02 AM [SEVERE]    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
11:53:02 AM [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
11:53:02 AM [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
11:53:02 AM [SEVERE] Encountered an unexpected exception AbstractMethodError
java.lang.AbstractMethodError: net.aufdemrand.sentry.BodyguardTeleportStuckAction.run(Lnet/citizensnpcs/api/npc/NPC;Lnet/citizensnpcs/api/ai/Navigator;)V
at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:145)
at net.citizensnpcs.npc.ai.CitizensNavigator.update(CitizensNavigator.java:166)
at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:163)
at net.citizensnpcs.npc.entity.CitizensHumanNPC.update(CitizensHumanNPC.java:138)
at net.citizensnpcs.npc.entity.EntityHumanNPC.h_(EntityHumanNPC.java:85)
at net.minecraft.server.World.entityJoinedWorld(World.java:1245)
at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:511)
at net.minecraft.server.World.playerJoinedWorld(World.java:1227)
at net.minecraft.server.World.tickEntities(World.java:1125)
at net.minecraft.server.WorldServer.tickEntities(WorldServer.java:428)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:564)
at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
11:53:02 AM [SEVERE] This crash report has been saved to: C:\Users\Leslie\Documents\Minecraft Server.\crash-reports\crash-2012-09-15_11.53.02-server.txt
11:53:20 AM [WARNING][Server] The main thread failed to respond after 10 seconds
11:53:20 AM [WARNING][Server] What follows is the stack trace of the main thread
11:53:20 AM [WARNING][Server]    at java.lang.Thread.sleep(Native Method)
11:53:20 AM [WARNING][Server]    at net.minecraft.server.DedicatedServer.a(DedicatedServer.java:195)
11:53:20 AM [WARNING][Server]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
11:53:20 AM [WARNING][Server]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
11:53:32 AM [WARNING][Server] The main thread is still stuck, current loop line is:
11:53:32 AM [WARNING][Server]    at net.minecraft.server.DedicatedServer.a(DedicatedServer.java:195)

**Comment by jrbudda** [comment]
Read the big red text on the wiki.
