### ISSUE TITLE
Error with Sentry, Console Error

### ISSUE THREAD

**Issue by rune2635** [jrbudda/Sentry#264]
THIS IS LIVE FROM THE CONSOLE!

[15:13:39 INFO]: xXRuneMCXx issued server command: /npc create Gangster  --trait sentry
[15:13:39 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/World
[15:13:39 WARN]:        at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:134)
[15:13:39 WARN]:        at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:116)
[15:13:39 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:109)
[15:13:39 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:382)
[15:13:39 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:13:39 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:13:39 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:13:39 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[15:13:39 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
[15:13:39 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[15:13:39 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
[15:13:39 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[15:13:39 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:13:39 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:13:39 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640)
[15:13:39 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[15:13:39 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[15:13:39 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:13:39 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:13:39 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:13:39 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:13:39 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[15:13:39 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[15:13:39 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
[15:13:39 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[15:13:39 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[15:13:39 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[15:13:39 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:13:39 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.World
[15:13:39 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[15:13:39 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[15:13:39 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[15:13:39 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[15:13:39 WARN]:        ... 28 more

**Comment by mcmonkey4eva** [comment]
Wrong version, can get the correct one from our broken wiki http://wiki.citizensnpcs.co/Sentry#Updates
