### ISSUE TITLE
how can i use sentry bukkit 1.8.8 RO1?

### ISSUE THREAD

**Issue by kutonoty** [jrbudda/Sentry#265]
Error occurred while enabling Sentry v1.9.0 (Is it up to date?)
java.lang.IllegalArgumentException: trait name already registered
    at net.citizensnpcs.npc.CitizensTraitFactory.registerTrait(CitizensTraitFactory.java:157) ~[?:?]
    at net.aufdemrand.sentry.Sentry.onEnable(Sentry.java:1403) ~[?:?]
    at

**Comment by mcmonkey4eva** [comment]
By not doing whatever you just did.

You either used `/reload` (bad) or somehow installed Sentry twice (bad)
