### ISSUE TITLE
Sentry Error please report this error [see console]

### ISSUE THREAD

**Issue by BeniBeast** [jrbudda/Sentry#266]
[20:11:15 WARN]:    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1158)
[20:11:15 WARN]:    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(SourceFile:37)
[20:11:15 WARN]:    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(SourceFile:9)
[20:11:15 WARN]:    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[20:11:15 WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:11:15 WARN]:    at java.util.concurrent.FutureTask.run(Unknown Source)
[20:11:15 WARN]:    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[20:11:15 WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:679)
[20:11:15 WARN]:    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:361)
[20:11:15 WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:635)
[20:11:15 WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:539)
[20:11:15 WARN]:    at java.lang.Thread.run(Unknown Source)
[20:11:15 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.World
[20:11:15 WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
[20:11:15 WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
[20:11:15 WARN]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[20:11:15 WARN]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[20:11:15 WARN]:    ... 30 more

**Comment by mcmonkey4eva** [comment]
You're using Sentry for 1.7.10 on a 1.9 server.
See here for a newer plugin compat with 1.9: https://github.com/mcmonkey4eva/Sentinel/blob/master/README.md
