### ISSUE TITLE
Sentry Error 1.10

### ISSUE THREAD

**Issue by enterih** [jrbudda/Sentry#267]
Don't work
I use /trait sentry

25.06 18:47:46 [Server] WARN java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R2/Packet
25.06 18:47:46 [Server] WARN at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:137)
25.06 18:47:46 [Server] WARN at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:119)
25.06 18:47:46 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:110)
25.06 18:47:46 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:89)
25.06 18:47:46 [Server] WARN at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
25.06 18:47:46 [Server] WARN at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
25.06 18:47:46 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
25.06 18:47:46 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
25.06 18:47:46 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
25.06 18:47:46 [Server] WARN at java.lang.reflect.Method.invoke(Unknown Source)
25.06 18:47:46 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
25.06 18:47:46 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
25.06 18:47:46 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
25.06 18:47:46 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
25.06 18:47:46 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
25.06 18:47:46 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
25.06 18:47:46 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
25.06 18:47:46 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
25.06 18:47:46 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
25.06 18:47:46 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
25.06 18:47:46 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
25.06 18:47:46 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
25.06 18:47:46 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
25.06 18:47:46 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
25.06 18:47:46 [Server] WARN at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
25.06 18:47:46 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733)
25.06 18:47:46 [Server] WARN at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
25.06 18:47:46 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
25.06 18:47:46 [Multicraft] Skipped 13 lines due to rate limit (30/s)

**Comment by mcmonkey4eva** [comment]
https://github.com/mcmonkey4eva/Sentinel/blob/master/README.md
