### ISSUE TITLE
N.V.M.

### ISSUE THREAD

**Issue by AviV0** [jrbudda/Sentry#269]
[14:41:20 INFO]: QuintiniusVelgix issued server command: /npc create Isaac --trait sentry
[14:41:20 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/World
[14:41:20 WARN]: 	at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:134)
[14:41:20 WARN]: 	at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:116)
[14:41:20 WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:110)
[14:41:20 WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:463)
[14:41:20 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:41:20 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:41:20 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:41:20 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:41:20 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[14:41:20 WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[14:41:20 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[14:41:20 WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
[14:41:20 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:41:20 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[14:41:20 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:628)
[14:41:20 WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1338)
[14:41:20 WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1198)
[14:41:20 WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:37)
[14:41:20 WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:9)
[14:41:20 WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[14:41:20 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:41:20 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:41:20 WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[14:41:20 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696)
[14:41:20 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371)
[14:41:20 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651)
[14:41:20 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555)
[14:41:20 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:41:20 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.World
[14:41:20 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81)
[14:41:20 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:76)
[14:41:20 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[14:41:20 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[14:41:20 WARN]: 	... 28 more

**Comment by AviV0** [comment]
this is useless.
forgot about sentinel
