### ISSUE TITLE
i need help 

### ISSUE THREAD

**Issue by Darkdeadpool3485** [jrbudda/Sentry#270]
/trait sentry
>.... [19:01:38 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/Packet
>.... [19:01:38 WARN]: at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:134)
>.... [19:01:38 WARN]: at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:116)
>.... [19:01:38 WARN]: at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:112)
>.... [19:01:38 WARN]: at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:91)
>.... [19:01:38 WARN]: at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
>.... [19:01:38 WARN]: at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
>.... [19:01:38 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>.... [19:01:38 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>.... [19:01:38 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [19:01:38 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [19:01:38 WARN]: at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
>.... [19:01:38 WARN]: at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
>.... [19:01:38 WARN]: at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
>.... [19:01:38 WARN]: at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
>.... [19:01:38 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [19:01:38 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [19:01:38 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:753)
>.... [19:01:38 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1837)
>.... [19:01:38 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1645)
>.... [19:01:38 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
>.... [19:01:38 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
>.... [19:01:38 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
>.... [19:01:38 WARN]: at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
>.... [19:01:38 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [19:01:38 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [19:01:38 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [19:01:38 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081)
>.... [19:01:38 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074)
>.... [19:01:38 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [19:01:38 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1035)
>.... [19:01:38 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950)
>.... [19:01:38 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [19:01:38 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.Packet
>.... [19:01:38 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105)
>.... [19:01:38 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
>.... [19:01:38 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
>.... [19:01:38 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
>.... [19:01:38 WARN]: ... 32 more

**Comment by mcmonkey4eva** [comment]
Sentry hasn't been a thing for 6 or 7 years man.
Use Sentinel: https://github.com/mcmonkeyprojects/Sentinel/blob/master/README.md

**Comment by Darkdeadpool3485** [comment]
i still got the error message when i upload it
