### ISSUE TITLE
Server crash with .9.9 and 2.0.2 - setting path

### ISSUE THREAD

**Issue by rossyell** [jrbudda/Sentry#30]
The below crash reguarly occuring with the server using using the latest version of everything while trying to set/ edit path  Still something wrong with the path editor - and still had my sentry dashing from one spot to the other.

Great work - and love the quick response you make.

[INFO] EpicEzzrin issued server command: /npc path
13:37:08 [SEVERE] Could not pass event PlayerInteractEvent to Citizens
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
        at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:114)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:547)
        at net.minecraft.server.Packet14BlockDig.handle(SourceFile:46)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
        at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
        at net.minecraft.server.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:577)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.util.IllegalFormatConversionException: d != java.lang.String
        at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4023)
        at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2726)
        at java.util.Formatter$FormatSpecifier.print(Formatter.java:2680)
        at java.util.Formatter.format(Formatter.java:2466)
        at java.util.Formatter.format(Formatter.java:2400)
        at java.lang.String.format(String.java:2845)
        at net.citizensnpcs.util.Messaging.getFormatted(Messaging.java:28)
        at net.citizensnpcs.util.Messaging.sendF(Messaging.java:70)
        at net.citizensnpcs.trait.waypoint.LinearWaypointProvider$1.onPlayerInteract(LinearWaypointProvider.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:613)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
        ... 16 more

**Comment by jrbudda** [comment]
I've seen this a few times, its not a sentry problem per se. something in citizens2. I will take a look though.

**Comment by jrbudda** [comment]
This appears to happen when you try to make a waypoint that is too far from the last waypoint. Something is wrong with the error message it is supposed to display.

**Comment by rossyell** [comment]
Genuinely - you rock !.  Thanks for looking into it.

**Comment by jrbudda** [comment]
Fixed in latest citizens build.

**Comment by rossyell** [comment]
Thanks – have loaded up 374.  No crashes – did have an issue with one of the sentries fading in and out – maybe going missing and will watch that.

Look forward to seeing how this project progresses.  Once you are happy it is stable could start looking into making it work with WorldGuard – both to set boundaries that sentries will not walk out of and to set areas for sentries to protect.

Anyway – lets see how it goes.

Thanks
