### ISSUE TITLE
mcMMO compatibility errors

### ISSUE THREAD

**Issue by st392** [jrbudda/Sentry#35]
When a sentry npc tries to attack a player it creates errors in the console for each hit.  I am guessing it is trying to pass stats to mcMMO.  One of the errors is as follows:

2012-09-29 15:29:10 [SEVERE] Could not pass event EntityDamageByEntityEvent to mcMMO
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:80)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:364)
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:386)
        at net.minecraft.server.EntityLiving.damageEntity(EntityLiving.java:591)
        at net.minecraft.server.EntityHuman.damageEntity(EntityHuman.java:595)
        at net.minecraft.server.EntityPlayer.damageEntity(EntityPlayer.java:353)
        at net.minecraft.server.EntityHuman.attack(EntityHuman.java:762)
        at net.citizensnpcs.npc.ai.MCTargetStrategy.update(MCTargetStrategy.java:102)
        at net.citizensnpcs.npc.ai.CitizensNavigator.update(CitizensNavigator.java:184)
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:179)
        at net.citizensnpcs.npc.entity.CitizensHumanNPC.update(CitizensHumanNPC.java:133)
        at net.citizensnpcs.npc.entity.EntityHumanNPC.h_(EntityHumanNPC.java:124)
        at net.minecraft.server.World.entityJoinedWorld(World.java:1245)
        at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:511)
        at net.minecraft.server.World.playerJoinedWorld(World.java:1227)
        at net.minecraft.server.World.tickEntities(World.java:1125)
        at net.minecraft.server.WorldServer.tickEntities(WorldServer.java:428)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:563)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
        at com.gmail.nossr50.util.Skills.abilityCheck(Skills.java:401)
        at com.gmail.nossr50.util.Combat.combatChecks(Combat.java:76)
        at com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:98)
        at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
        ... 25 more

**Comment by jrbudda** [comment]
I can't fix errors in McMMO. This has to be reported to them.
