### ISSUE TITLE
BodyGuard issue

### ISSUE THREAD

**Issue by Thegman34** [jrbudda/Sentry#46]
Hey Jrbudda,

 First off thanks for making this awesome mod. I'm Having a problem with what seems to be the Guard command. I know I'm in his range, because if i spawn zombies right next to me hell shoot at them no problem. When i type "/sentry guard thegman34" All it gives me is " Stormcaller could not find thegman34 in range". I'm not too worried about having him defend other npcs atm, i just want him to guard myself. Thanks!

**Comment by Thegman34** [comment]
Also, if the sentry has a target, for example if its night and hes targeting a skeleton, and i try and use the "/sentry equip" command im getting this error
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 10/16/12 4:16 AM
Description: Exception in server tick loop

java.lang.AbstractMethodError: net.aufdemrand.sentry.GiveUpStuckAction.run(Lnet/citizensnpcs/api/npc/NPC;Lnet/citizensnpcs/api/ai/Navigator;)V
    at net.citizensnpcs.npc.ai.CitizensNavigator.updateStationaryStatus(CitizensNavigator.java:166)
    at net.citizensnpcs.npc.ai.CitizensNavigator.update(CitizensNavigator.java:144)
    at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:163)
    at net.citizensnpcs.npc.entity.CitizensHumanNPC.update(CitizensHumanNPC.java:138)
    at net.citizensnpcs.npc.entity.EntityHumanNPC.h_(EntityHumanNPC.java:85)
    at net.minecraft.server.World.entityJoinedWorld(World.java:1245)
    at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:511)
    at net.minecraft.server.World.playerJoinedWorld(World.java:1227)
    at net.minecraft.server.World.tickEntities(World.java:1125)
    at net.minecraft.server.WorldServer.tickEntities(WorldServer.java:428)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:563)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

**Comment by jrbudda** [comment]
Make sure your Citizens2 is up to date. And /sentry guard is case sensitive

**Comment by Thegman34** [comment]
Yeah, my Citizens 2 was downloaded last night and with the newest build. Thanks, the Case sensitive worked. And the crash is avoidable so i'm not worried. Thanks so much!
