### ISSUE TITLE
Error messages in the server.log 

### ISSUE THREAD

**Issue by SBlack08** [jrbudda/Sentry#58]
[INFO] This server is running CraftBukkit version git-Bukkit-1.4.2-R0.2-1-g3d8a353-b2457jnks (MC: 1.4.2) (Implementing API version 1.4.2-R0.3-SNAPSHOT)
[INFO] [Sentry] Loading Sentry v1.2.2
[INFO] [Citizens] Loading Citizens v2.0.4-SNAPSHOT (build 566)
[INFO] [Builder] Loading Builder v0.6.2
[INFO] [DtlCitizensTrader] Loading DtlCitizensTrader v2.0RC v0.5
[INFO] [Vault] Enabling Vault v1.2.18-b229
[INFO] [iConomy] Enabling iConomy v7.0

2012-11-14 22:12:24 [SEVERE] Could not pass event NPCRightClickEvent to DtlCitizensTrader v2.0RC v0.5
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:235)
    at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1031)
    at net.minecraft.server.Packet7UseEntity.handle(SourceFile:36)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:111)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:578)
    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:215)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:495)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:428)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)
Caused by: java.lang.NoClassDefFoundError: net/aufdemrand/denizen/Denizen
    at net.dtl.citizens.trader.NpcEcoManager.onNPCRightCLick(NpcEcoManager.java:243)
    at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 22 more

**Comment by XxCoolGamesxX** [comment]
Hey. Your error is form: https://github.com/Dandielo/DtlCitizensTrader/issues. Not of Sentry Plugin. Nope it help you.

**Comment by SBlack08** [comment]
oh :D thanks
