### ISSUE TITLE
Compatibility error with mcMMO

### ISSUE THREAD

**Issue by Avasam** [jrbudda/Sentry#61]
This is surely somekind of the same errors that occurs with Heros:
Everytime a Sentry hit or get hit, I get spammed with an error log and McMMO damage modification does not occur. Maybe it's because of the damage modification that Sentries have? I haven't found a way to deactivate it completely to test it.

Craftbukkit 1.4.5 R0.2
Citizens2 Build #578
Sentry version 1.2.2a
McMMO version 1.3.11 (for CB 1.3.1-R1.0)

Error log:
2012-11-22 22:43:31 [SEVERE] Could not pass event EntityDamageByEntityEvent to mcMMO v1.3.11-b1030
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:80)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:377)
    at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:399)
    at net.minecraft.server.EntityLiving.damageEntity(EntityLiving.java:658)
    at net.minecraft.server.EntityMonster.damageEntity(EntityMonster.java:39)
    at net.minecraft.server.EntityHuman.attack(EntityHuman.java:794)
    at net.citizensnpcs.npc.ai.MCTargetStrategy.update(MCTargetStrategy.java:105)
    at net.citizensnpcs.npc.ai.CitizensNavigator.update(CitizensNavigator.java:192)
    at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:219)
    at net.citizensnpcs.npc.entity.CitizensHumanNPC.update(CitizensHumanNPC.java:139)
    at net.citizensnpcs.npc.entity.EntityHumanNPC.j_(EntityHumanNPC.java:143)
    at net.minecraft.server.World.entityJoinedWorld(World.java:1333)
    at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:546)
    at net.minecraft.server.World.playerJoinedWorld(World.java:1315)
    at net.minecraft.server.World.tickEntities(World.java:1193)
    at net.minecraft.server.WorldServer.tickEntities(WorldServer.java:444)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:577)
    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.NullPointerException
    at com.gmail.nossr50.util.Skills.abilityCheck(Skills.java:401)
    at com.gmail.nossr50.util.Combat.combatChecks(Combat.java:76)
    at com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 24 more

**Comment by Matterom** [comment]
That is entirely a problem with MCmmo, they fixed it but a change in the citizens 2 core changed how npcs were recognized(Fixed some other bugs, broke mcmmo) ,while annoying this message has no real effect on the sentry's themselfs, so mcmmo has to update their plugin to match it with the latest citizens

**Comment by Avasam** [comment]
Well, I'll wait for mcMMO to update then. Thanks for clearing the obscurity on my problem
