### ISSUE TITLE
Errors when using Sentry

### ISSUE THREAD

**Issue by jesterstud** [jrbudda/Sentry#68]
I have loaded Citizens 2.0.4 along with the latest Sentry.jar. I am able to create the npc, but as soon as I set /trait sentry  I get an error telling me to report.

I was not sure whether another plugin was the problem, so I created a bukkit server with just Citizens and Sentry and tried to create a simple sentry. I got the same error "please report this" even though npc was marked as sentry.

I was able to set waypoints and equip the npc, but threw all sorts of errors trying to set the target.

The problems persist even when restarting the server. 

I appreciate any guidance you can offer!

2012-12-17 23:06:22 [INFO] Starting minecraft server version 1.4.5
2012-12-17 23:06:22 [INFO] Loading properties
2012-12-17 23:06:22 [INFO] Default game type: SURVIVAL
2012-12-17 23:06:22 [INFO] Generating keypair
2012-12-17 23:06:23 [INFO] Starting Minecraft server on *:25565
2012-12-17 23:06:23 [INFO] This server is running CraftBukkit version git-Bukkit-1.4.5-R0.2-b2488jnks (MC: 1.4.5) (Implementing API version 1.4.5-R0.2)
2012-12-17 23:06:23 [WARNING] Failed to load white-list: java.io.FileNotFoundException: .\white-list.txt (The system cannot find the file specified)
2012-12-17 23:06:23 [INFO] Preparing level "world"
2012-12-17 23:06:23 [INFO] Preparing start region for level 0 (Seed: -9095144965446292133)
2012-12-17 23:06:24 [INFO] ----- Bukkit Auto Updater -----
2012-12-17 23:06:24 [INFO] It appears that you're running a Beta Build, when you've specified in bukkit.yml that you prefer to run Recommended Builds.
2012-12-17 23:06:24 [INFO] If you would like to be kept informed about new Beta Build releases, it is recommended that you change 'preferred-channel' in your bukkit.yml to 'beta'.
2012-12-17 23:06:24 [INFO] With that set, you will be told whenever a new version is available for download, so that you can always keep up to date and secure with the latest fixes.
2012-12-17 23:06:24 [INFO] If you would like to disable this warning, simply set 'suggest-channels' to false in bukkit.yml.
2012-12-17 23:06:24 [INFO] ----- ------------------- -----
2012-12-17 23:06:24 [INFO] Preparing spawn area: 12%
2012-12-17 23:06:25 [INFO] Preparing spawn area: 24%
2012-12-17 23:06:26 [INFO] Preparing spawn area: 40%
2012-12-17 23:06:27 [INFO] Preparing spawn area: 57%
2012-12-17 23:06:28 [INFO] Preparing spawn area: 69%
2012-12-17 23:06:29 [INFO] Preparing spawn area: 85%
2012-12-17 23:06:30 [INFO] Preparing spawn area: 97%
2012-12-17 23:06:30 [INFO] Preparing start region for level 1 (Seed: -9095144965446292133)
2012-12-17 23:06:31 [INFO] Preparing spawn area: 20%
2012-12-17 23:06:32 [INFO] Preparing spawn area: 48%
2012-12-17 23:06:33 [INFO] Preparing spawn area: 69%
2012-12-17 23:06:34 [INFO] Preparing spawn area: 93%
2012-12-17 23:06:35 [INFO] Preparing start region for level 2 (Seed: -9095144965446292133)
2012-12-17 23:06:35 [INFO] Preparing spawn area: 36%
2012-12-17 23:06:36 [INFO] Preparing spawn area: 85%
2012-12-17 23:06:37 [INFO] Done (13.751s)! For help, type "help" or "?"
2012-12-17 23:06:41 [INFO] CONSOLE: Stopping the server..[m
2012-12-17 23:06:42 [INFO] Stopping server
2012-12-17 23:06:42 [INFO] Saving players
2012-12-17 23:06:42 [WARNING] DSCT: socket closed
2012-12-17 23:06:42 [INFO] Saving worlds
2012-12-17 23:06:42 [INFO] Closing listening thread
2012-12-17 23:06:42 [INFO] Saving chunks for level 'world'/Overworld
2012-12-17 23:06:43 [INFO] Saving chunks for level 'world_nether'/Nether
2012-12-17 23:06:44 [INFO] Saving chunks for level 'world_the_end'/The End
2012-12-17 23:06:44 [INFO] Stopping server
2012-12-17 23:07:51 [INFO] Starting minecraft server version 1.4.5
2012-12-17 23:07:51 [INFO] Loading properties
2012-12-17 23:07:51 [INFO] Default game type: SURVIVAL
2012-12-17 23:07:51 [INFO] Generating keypair
2012-12-17 23:07:51 [INFO] Starting Minecraft server on *:25565
2012-12-17 23:07:51 [INFO] This server is running CraftBukkit version git-Bukkit-1.4.5-R0.2-b2488jnks (MC: 1.4.5) (Implementing API version 1.4.5-R0.2)
2012-12-17 23:07:52 [INFO] [Citizens] Loading Citizens v2.0.4-SNAPSHOT (build 597)
2012-12-17 23:07:52 [INFO] Preparing level "world"
2012-12-17 23:07:52 [INFO] Preparing start region for level 0 (Seed: -9095144965446292133)
2012-12-17 23:07:52 [INFO] ----- Bukkit Auto Updater -----
2012-12-17 23:07:52 [INFO] It appears that you're running a Beta Build, when you've specified in bukkit.yml that you prefer to run Recommended Builds.
2012-12-17 23:07:52 [INFO] If you would like to be kept informed about new Beta Build releases, it is recommended that you change 'preferred-channel' in your bukkit.yml to 'beta'.
2012-12-17 23:07:52 [INFO] With that set, you will be told whenever a new version is available for download, so that you can always keep up to date and secure with the latest fixes.
2012-12-17 23:07:52 [INFO] If you would like to disable this warning, simply set 'suggest-channels' to false in bukkit.yml.
2012-12-17 23:07:52 [INFO] ----- ------------------- -----
2012-12-17 23:07:53 [INFO] Preparing start region for level 1 (Seed: -9095144965446292133)
2012-12-17 23:07:53 [INFO] Preparing spawn area: 0%
2012-12-17 23:07:53 [INFO] Preparing start region for level 2 (Seed: -9095144965446292133)
2012-12-17 23:07:53 [INFO] [Citizens] Enabling Citizens v2.0.4-SNAPSHOT (build 597)
2012-12-17 23:07:53 [INFO] Creating file: config.yml
2012-12-17 23:07:54 [INFO] Creating file: saves.yml
2012-12-17 23:07:54 [INFO] [Citizens] Using locale en_US.
2012-12-17 23:07:54 [INFO] [Citizens] Save method set to YamlStorage {file=plugins\Citizens\saves.yml}.
2012-12-17 23:07:54 [INFO] [Citizens] Unable to use economy handling. Has Vault been enabled?
2012-12-17 23:07:54 [INFO] Server permissions file permissions.yml is empty, ignoring it
2012-12-17 23:07:54 [INFO] Done (2.211s)! For help, type "help" or "?"
2012-12-17 23:07:54 [INFO] [Citizens] Loaded 0 NPCs.
2012-12-17 23:08:07 [INFO] CONSOLE: Stopping the server..[m
2012-12-17 23:08:07 [INFO] Stopping server
2012-12-17 23:08:07 [INFO] [Citizens] Disabling Citizens v2.0.4-SNAPSHOT (build 597)
2012-12-17 23:08:07 [INFO] Saving players
2012-12-17 23:08:07 [WARNING] DSCT: socket closed
2012-12-17 23:08:07 [INFO] Saving worlds
2012-12-17 23:08:07 [INFO] Saving chunks for level 'world'/Overworld
2012-12-17 23:08:07 [INFO] Closing listening thread
2012-12-17 23:08:08 [INFO] Saving chunks for level 'world_nether'/Nether
2012-12-17 23:08:09 [INFO] Saving chunks for level 'world_the_end'/The End
2012-12-17 23:08:35 [INFO] Starting minecraft server version 1.4.5
2012-12-17 23:08:35 [INFO] Loading properties
2012-12-17 23:08:35 [INFO] Default game type: SURVIVAL
2012-12-17 23:08:35 [INFO] Generating keypair
2012-12-17 23:08:35 [INFO] Starting Minecraft server on *:25565
2012-12-17 23:08:36 [INFO] This server is running CraftBukkit version git-Bukkit-1.4.5-R0.2-b2488jnks (MC: 1.4.5) (Implementing API version 1.4.5-R0.2)
2012-12-17 23:08:36 [INFO] [Citizens] Loading Citizens v2.0.4-SNAPSHOT (build 597)
2012-12-17 23:08:36 [INFO] [Sentry] Loading Sentry v1.2.4
2012-12-17 23:08:36 [INFO] Preparing level "world"
2012-12-17 23:08:36 [INFO] Preparing start region for level 0 (Seed: -9095144965446292133)
2012-12-17 23:08:37 [INFO] ----- Bukkit Auto Updater -----
2012-12-17 23:08:37 [INFO] It appears that you're running a Beta Build, when you've specified in bukkit.yml that you prefer to run Recommended Builds.
2012-12-17 23:08:37 [INFO] If you would like to be kept informed about new Beta Build releases, it is recommended that you change 'preferred-channel' in your bukkit.yml to 'beta'.
2012-12-17 23:08:37 [INFO] With that set, you will be told whenever a new version is available for download, so that you can always keep up to date and secure with the latest fixes.
2012-12-17 23:08:37 [INFO] If you would like to disable this warning, simply set 'suggest-channels' to false in bukkit.yml.
2012-12-17 23:08:37 [INFO] ----- ------------------- -----
2012-12-17 23:08:37 [INFO] Preparing start region for level 1 (Seed: -9095144965446292133)
2012-12-17 23:08:37 [INFO] Preparing spawn area: 16%
2012-12-17 23:08:37 [INFO] Preparing start region for level 2 (Seed: -9095144965446292133)
2012-12-17 23:08:38 [INFO] [Citizens] Enabling Citizens v2.0.4-SNAPSHOT (build 597)
2012-12-17 23:08:38 [INFO] [Citizens] Using locale en_US.
2012-12-17 23:08:38 [INFO] [Citizens] Save method set to YamlStorage {file=plugins\Citizens\saves.yml}.
2012-12-17 23:08:38 [INFO] [Citizens] Unable to use economy handling. Has Vault been enabled?
2012-12-17 23:08:38 [INFO] [Sentry] Enabling Sentry v1.2.4
2012-12-17 23:08:38 [INFO] [Sentry] Could not register with Denizen
2012-12-17 23:08:38 [INFO] [Sentry] Could not find or register with Towny
2012-12-17 23:08:38 [INFO] [Sentry] Could not find or register with Factions.
2012-12-17 23:08:38 [INFO] [Sentry] Could not find or register with War. 
2012-12-17 23:08:38 [INFO] [Sentry] Could not find or register with SimpleClans. 
2012-12-17 23:08:38 [INFO] Server permissions file permissions.yml is empty, ignoring it
2012-12-17 23:08:38 [INFO] Done (2.145s)! For help, type "help" or "?"
2012-12-17 23:08:38 [INFO] [Citizens] Loaded 0 NPCs.
2012-12-17 23:08:51 [INFO] jesterstud[/192.168.1.6:54747] logged in with entity id 236 at ([world] 247.5, 71.62000000476837, 250.5)
2012-12-17 23:09:07 [INFO] jesterstud issued server command: /npc help
2012-12-17 23:09:20 [INFO] jesterstud issued server command: /npc create Bob
2012-12-17 23:09:49 [INFO] jesterstud issued server command: /trait sentry
2012-12-17 23:09:49 [SEVERE] java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/Packet
2012-12-17 23:09:49 [SEVERE]    at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:132)
2012-12-17 23:09:49 [SEVERE]    at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:111)
2012-12-17 23:09:49 [SEVERE]    at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:55)
2012-12-17 23:09:49 [SEVERE]    at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:35)
2012-12-17 23:09:49 [SEVERE]    at net.citizensnpcs.command.command.TraitCommands.toggle(TraitCommands.java:141)
2012-12-17 23:09:49 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-12-17 23:09:49 [SEVERE]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2012-12-17 23:09:49 [SEVERE]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2012-12-17 23:09:49 [SEVERE]    at java.lang.reflect.Method.invoke(Unknown Source)
2012-12-17 23:09:49 [SEVERE]    at net.citizensnpcs.command.CommandManager.executeMethod(CommandManager.java:140)
2012-12-17 23:09:49 [SEVERE]    at net.citizensnpcs.command.CommandManager.execute(CommandManager.java:94)
2012-12-17 23:09:49 [SEVERE]    at net.citizensnpcs.Citizens.onCommand(Citizens.java:153)
2012-12-17 23:09:49 [SEVERE]    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2012-12-17 23:09:49 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
2012-12-17 23:09:49 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:502)
2012-12-17 23:09:49 [SEVERE]    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:985)
2012-12-17 23:09:49 [SEVERE]    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:903)
2012-12-17 23:09:49 [SEVERE]    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:858)
2012-12-17 23:09:49 [SEVERE]    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
2012-12-17 23:09:49 [SEVERE]    at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
2012-12-17 23:09:49 [SEVERE]    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:113)
2012-12-17 23:09:49 [SEVERE]    at net.minecraft.server.ServerConnection.b(SourceFile:39)
2012-12-17 23:09:49 [SEVERE]    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
2012-12-17 23:09:49 [SEVERE]    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
2012-12-17 23:09:49 [SEVERE]    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
2012-12-17 23:09:49 [SEVERE]    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
2012-12-17 23:09:49 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
2012-12-17 23:09:49 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
2012-12-17 23:09:49 [SEVERE] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_5.Packet
2012-12-17 23:09:49 [SEVERE]    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:34)
2012-12-17 23:09:49 [SEVERE]    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
2012-12-17 23:09:49 [SEVERE]    at java.lang.ClassLoader.loadClass(Unknown Source)
2012-12-17 23:09:49 [SEVERE]    at java.lang.ClassLoader.loadClass(Unknown Source)
2012-12-17 23:09:49 [SEVERE]    ... 28 more
2012-12-17 23:10:31 [INFO] jesterstud issued server command: /npc help 4
2012-12-17 23:10:41 [INFO] jesterstud issued server command: /npc help 3
2012-12-17 23:10:56 [INFO] jesterstud issued server command: /npc help 2
2012-12-17 23:11:02 [INFO] jesterstud issued server command: /npc path
2012-12-17 23:12:49 [INFO] jesterstud issued server command: /gamemode 1
2012-12-17 23:12:49 [INFO] jesterstud: Set own game mode to CREATIVE mode[m
2012-12-17 23:13:16 [INFO] jesterstud issued server command: /npc path
2012-12-17 23:13:33 [INFO] jesterstud issued server command: /npc equip
2012-12-17 23:14:56 [INFO] jesterstud issued server command: /npc playerlist
2012-12-17 23:16:02 [INFO] jesterstud issued server command: /npc help
2012-12-17 23:16:16 [INFO] jesterstud issued server command: /npc help 4
2012-12-17 23:16:26 [INFO] jesterstud issued server command: /npc help 2
2012-12-17 23:16:37 [INFO] jesterstud issued server command: /npc help 3
2012-12-17 23:16:52 [INFO] jesterstud issued server command: /sentry help
2012-12-17 23:17:21 [INFO] jesterstud issued server command: /sentry target
2012-12-17 23:17:32 [INFO] jesterstud issued server command: /sentry target list
2012-12-17 23:17:32 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'sentry' in plugin Sentry v1.2.4
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:502)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:985)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:903)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:858)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:113)
    at net.minecraft.server.ServerConnection.b(SourceFile:39)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.NullPointerException
    at net.aufdemrand.sentry.Sentry.onCommand(Sentry.java:1173)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    ... 15 more
2012-12-17 23:17:45 [INFO] jesterstud issued server command: /sentry target add spider
2012-12-17 23:18:54 [INFO] jesterstud issued server command: /sentry target add entity:spider
2012-12-17 23:18:54 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'sentry' in plugin Sentry v1.2.4
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:502)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:985)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:903)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:858)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:113)
    at net.minecraft.server.ServerConnection.b(SourceFile:39)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.NullPointerException
    at net.aufdemrand.sentry.Sentry.onCommand(Sentry.java:1147)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    ... 15 more
2012-12-17 23:19:05 [INFO] jesterstud issued server command: /sentry target list
2012-12-17 23:19:05 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'sentry' in plugin Sentry v1.2.4
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:502)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:985)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:903)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:858)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:113)
    at net.minecraft.server.ServerConnection.b(SourceFile:39)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.NullPointerException
    at net.aufdemrand.sentry.Sentry.onCommand(Sentry.java:1173)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    ... 15 more
2012-12-17 23:21:03 [INFO] jesterstud lost connection: disconnect.quitting
2012-12-17 23:21:03 [INFO] Connection reset
2012-12-17 23:21:10 [INFO] CONSOLE: Stopping the server..[m
2012-12-17 23:21:10 [INFO] Stopping server
2012-12-17 23:21:10 [INFO] [Sentry] Disabling Sentry v1.2.4
2012-12-17 23:21:10 [INFO] [Sentry]  v1.2.4 disabled.
2012-12-17 23:21:10 [INFO] [Citizens] Disabling Citizens v2.0.4-SNAPSHOT (build 597)
2012-12-17 23:21:10 [INFO] Saving players
2012-12-17 23:21:10 [WARNING] DSCT: socket closed
2012-12-17 23:21:10 [INFO] Saving worlds
2012-12-17 23:21:10 [INFO] Closing listening thread
2012-12-17 23:21:10 [INFO] Saving chunks for level 'world'/Overworld
2012-12-17 23:21:11 [INFO] Saving chunks for level 'world_nether'/Nether
2012-12-17 23:21:11 [INFO] Saving chunks for level 'world_the_end'/The End
2012-12-17 23:41:55 [INFO] Starting minecraft server version 1.4.5
2012-12-17 23:41:55 [INFO] Loading properties
2012-12-17 23:41:55 [INFO] Default game type: SURVIVAL
2012-12-17 23:41:55 [INFO] Generating keypair
2012-12-17 23:41:56 [INFO] Starting Minecraft server on *:25565
2012-12-17 23:41:56 [INFO] This server is running CraftBukkit version git-Bukkit-1.4.5-R0.2-b2488jnks (MC: 1.4.5) (Implementing API version 1.4.5-R0.2)
2012-12-17 23:41:56 [INFO] [Citizens] Loading Citizens v2.0.4-SNAPSHOT (build 597)
2012-12-17 23:41:56 [INFO] [Sentry] Loading Sentry v1.2.4
2012-12-17 23:41:56 [INFO] Preparing level "world"
2012-12-17 23:41:56 [INFO] Preparing start region for level 0 (Seed: -9095144965446292133)
2012-12-17 23:41:57 [INFO] ----- Bukkit Auto Updater -----
2012-12-17 23:41:57 [INFO] It appears that you're running a Beta Build, when you've specified in bukkit.yml that you prefer to run Recommended Builds.
2012-12-17 23:41:57 [INFO] If you would like to be kept informed about new Beta Build releases, it is recommended that you change 'preferred-channel' in your bukkit.yml to 'beta'.
2012-12-17 23:41:57 [INFO] With that set, you will be told whenever a new version is available for download, so that you can always keep up to date and secure with the latest fixes.
2012-12-17 23:41:57 [INFO] If you would like to disable this warning, simply set 'suggest-channels' to false in bukkit.yml.
2012-12-17 23:41:57 [INFO] ----- ------------------- -----
2012-12-17 23:41:57 [INFO] Preparing start region for level 1 (Seed: -9095144965446292133)
2012-12-17 23:41:57 [INFO] Preparing spawn area: 16%
2012-12-17 23:41:58 [INFO] Preparing start region for level 2 (Seed: -9095144965446292133)
2012-12-17 23:41:58 [INFO] [Citizens] Enabling Citizens v2.0.4-SNAPSHOT (build 597)
2012-12-17 23:41:58 [INFO] [Citizens] Using locale en_US.
2012-12-17 23:41:58 [INFO] [Citizens] Save method set to YamlStorage {file=plugins\Citizens\saves.yml}.
2012-12-17 23:41:58 [INFO] [Citizens] Unable to use economy handling. Has Vault been enabled?
2012-12-17 23:41:58 [INFO] [Sentry] Enabling Sentry v1.2.4
2012-12-17 23:41:58 [INFO] [Sentry] Could not register with Denizen
2012-12-17 23:41:58 [INFO] [Sentry] Could not find or register with Towny
2012-12-17 23:41:58 [INFO] [Sentry] Could not find or register with Factions.
2012-12-17 23:41:58 [INFO] [Sentry] Could not find or register with War. 
2012-12-17 23:41:58 [INFO] [Sentry] Could not find or register with SimpleClans. 
2012-12-17 23:41:58 [INFO] Server permissions file permissions.yml is empty, ignoring it
2012-12-17 23:41:58 [INFO] Done (2.152s)! For help, type "help" or "?"
2012-12-17 23:41:58 [WARNING] [Citizens] Task #2 for Citizens v2.0.4-SNAPSHOT (build 597) generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/Packet
    at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:132)
    at net.aufdemrand.sentry.SentryTrait.load(SentryTrait.java:34)
    at net.citizensnpcs.npc.CitizensNPC.loadTrait(CitizensNPC.java:137)
    at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:124)
    at net.citizensnpcs.NPCDataStore.loadInto(NPCDataStore.java:44)
    at net.citizensnpcs.Citizens$1.run(Citizens.java:232)
    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:529)
    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_5.Packet
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:34)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 13 more
2012-12-17 23:42:17 [INFO] CONSOLE: Stopping the server..[m
2012-12-17 23:42:17 [INFO] Stopping server
2012-12-17 23:42:17 [INFO] [Sentry] Disabling Sentry v1.2.4
2012-12-17 23:42:17 [INFO] [Sentry]  v1.2.4 disabled.
2012-12-17 23:42:17 [INFO] [Citizens] Disabling Citizens v2.0.4-SNAPSHOT (build 597)
2012-12-17 23:42:17 [WARNING] DSCT: socket closed
2012-12-17 23:42:17 [INFO] Closing listening thread
2012-12-17 23:42:17 [INFO] Saving players
2012-12-17 23:42:17 [INFO] Saving worlds
2012-12-17 23:42:17 [INFO] Saving chunks for level 'world'/Overworld
2012-12-17 23:42:17 [INFO] Saving chunks for level 'world_nether'/Nether
2012-12-17 23:42:17 [INFO] Saving chunks for level 'world_the_end'/The End

**Comment by XxCoolGamesxX** [comment]
Download the new update of Sentry and Citizens: http://wiki.citizensnpcs.com/Sentry
