### ISSUE TITLE
Error on 1.4.5R1.0

### ISSUE THREAD

**Issue by ghost** [jrbudda/Sentry#70]
```
012-12-21 11:20:41 [WARNING] [Sentry] Task #130 for Sentry v1.2.4 generated an exception
java.lang.NoSuchMethodError: net.citizensnpcs.util.Util.sendPacketNearby(Lorg/bukkit/Location;Lnet/minecraft/server/v1_4_5/Packet;D)V
    at net.aufdemrand.sentry.SentryInstance$SentryLogic.run(SentryInstance.java:1292)
    at org.bukkit.craftbukkit.v1_4_5.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_5.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
    at net.minecraft.server.v1_4_5.MinecraftServer.r(MinecraftServer.java:516)
    at net.minecraft.server.v1_4_5.DedicatedServer.r(DedicatedServer.java:222)
    at net.minecraft.server.v1_4_5.MinecraftServer.q(MinecraftServer.java:480)
    at net.minecraft.server.v1_4_5.MinecraftServer.run(MinecraftServer.java:415)
    at net.minecraft.server.v1_4_5.ThreadServerApplication.run(SourceFile:856)
```

**Comment by XxCoolGamesxX** [comment]
Download the new update of Sentry and Citizens: http://wiki.citizensnpcs.com/Sentry
