### ISSUE TITLE
Sentry 1.3.2 not loading

### ISSUE THREAD

**Issue by c0dejunKie** [jrbudda/Sentry#98]
I am running the latest dev bukkit build and the latest citizens dev build and when i try to use sentry 1.3.2 I get this error:

2013-03-17 02:25:27 [SEVERE] Could not load 'plugins/Sentry_v1.3.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/aufdemrand/denizen/interfaces/RegistrationableInstance
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:184)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:307)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:231)
    at org.bukkit.craftbukkit.v1_5_R1.CraftServer.loadPlugins(CraftServer.java:261)
    at org.bukkit.craftbukkit.v1_5_R1.CraftServer.<init>(CraftServer.java:239)
    at net.minecraft.server.v1_5_R1.PlayerList.<init>(PlayerList.java:55)
    at net.minecraft.server.v1_5_R1.DedicatedPlayerList.<init>(SourceFile:11)
    at net.minecraft.server.v1_5_R1.DedicatedServer.init(DedicatedServer.java:109)
    at net.minecraft.server.v1_5_R1.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.v1_5_R1.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NoClassDefFoundError: net/aufdemrand/denizen/interfaces/RegistrationableInstance
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:173)
    ... 9 more
Caused by: java.lang.ClassNotFoundException: net.aufdemrand.denizen.interfaces.RegistrationableInstance
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:87)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 12 more

after this error I also see this:

2013-03-17 02:25:30 [SEVERE] [Citizens] Skipped broken or missing trait sentry while loading ID 9. Has the name changed?
2013-03-17 02:25:30 [SEVERE] [Citizens] Skipped broken or missing trait sentry while loading ID 18. Has the name changed?

but I pretty sure that this is cause just because sentry didnt load, any help would be greatly appreciated, thank you.

**Comment by XxCoolGamesxX** [comment]
You it the denizen plugin for work with new update of the plugin.

**Comment by c0dejunKie** [comment]
its working now with the latest version 1.3.3 and i do not have denizen and never have used it, is it a requirement or something like that?
